use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let docs_dir = Path::new(&manifest_dir).join("docs");
    let ru_dir = docs_dir.join("ru");
    let en_dir = docs_dir.join("en");
    let code_rs = Path::new(&manifest_dir).join("src/code.rs");

    let valid_codes = extract_diagnostic_codes(&code_rs);
    println!("cargo:warning=Found {} valid diagnostic codes", valid_codes.len());

    let mut codes_with_docs: HashSet<String> = HashSet::new();

    if ru_dir.exists() {
        for entry in fs::read_dir(&ru_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension().map(|e| e == "md").unwrap_or(false) {
                if let Some(stem) = path.file_stem() {
                    let code = stem.to_string_lossy().to_string();
                    if valid_codes.contains(&code) {
                        codes_with_docs.insert(code);
                    }
                }
            }
        }
    }

    println!("cargo:warning=Found {} documented codes", codes_with_docs.len());

    let mut generated = String::new();
    generated.push_str("// Auto-generated diagnostic documentation.\n");
    generated.push_str("// DO NOT EDIT - generated by build.rs\n\n");
    generated.push_str("use crate::DiagnosticCode;\n\n");

    generated.push_str("/// Documentation for a diagnostic.\n");
    generated.push_str("#[derive(Debug, Clone)]\n");
    generated.push_str("pub struct DiagnosticDocs {\n");
    generated.push_str("    /// Diagnostic name in Russian\n");
    generated.push_str("    pub name_ru: &'static str,\n");
    generated.push_str("    /// Diagnostic name in English\n");
    generated.push_str("    pub name_en: &'static str,\n");
    generated.push_str("    /// Full description in Russian (Markdown)\n");
    generated.push_str("    pub description_ru: &'static str,\n");
    generated.push_str("    /// Full description in English (Markdown)\n");
    generated.push_str("    pub description_en: &'static str,\n");
    generated.push_str("}\n\n");

    generated.push_str("impl DiagnosticDocs {\n");
    generated.push_str("    /// Empty documentation placeholder\n");
    generated.push_str("    pub const EMPTY: DiagnosticDocs = DiagnosticDocs {\n");
    generated.push_str("        name_ru: \"\",\n");
    generated.push_str("        name_en: \"\",\n");
    generated.push_str("        description_ru: \"\",\n");
    generated.push_str("        description_en: \"\",\n");
    generated.push_str("    };\n");
    generated.push_str("}\n\n");

    generated.push_str("/// Get documentation for a diagnostic code.\n");
    generated.push_str("#[allow(unreachable_patterns)]\n");
    generated.push_str("pub fn get_docs(code: DiagnosticCode) -> DiagnosticDocs {\n");
    generated.push_str("    match code {\n");

    let mut codes: Vec<_> = codes_with_docs.iter().collect();
    codes.sort();

    for code in &codes {
        let ru_path = ru_dir.join(format!("{}.md", code));
        let en_path = en_dir.join(format!("{}.md", code));

        let has_ru = ru_path.exists();
        let has_en = en_path.exists();

        if !has_ru && !has_en {
            continue;
        }

        let name_ru = if has_ru { extract_name_from_md(&ru_path) } else { code.to_string() };

        let name_en = if has_en { extract_name_from_md(&en_path) } else { code.to_string() };

        generated.push_str(&format!("        DiagnosticCode::{} => DiagnosticDocs {{\n", code));
        generated.push_str(&format!("            name_ru: {:?},\n", name_ru));
        generated.push_str(&format!("            name_en: {:?},\n", name_en));

        if has_ru {
            generated.push_str(&format!(
                "            description_ru: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/docs/ru/{}.md\")),\n",
                code
            ));
        } else {
            generated.push_str("            description_ru: \"\",\n");
        }

        if has_en {
            generated.push_str(&format!(
                "            description_en: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/docs/en/{}.md\")),\n",
                code
            ));
        } else {
            generated.push_str("            description_en: \"\",\n");
        }

        generated.push_str("        },\n");
    }

    generated.push_str("        _ => DiagnosticDocs::EMPTY,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n\n");

    generated.push_str("/// List of all diagnostic codes that have documentation.\n");
    generated.push_str("pub const DOCUMENTED_CODES: &[DiagnosticCode] = &[\n");
    for code in &codes {
        generated.push_str(&format!("    DiagnosticCode::{},\n", code));
    }
    generated.push_str("];\n");

    let dest_path = Path::new(&out_dir).join("docs_generated.rs");
    fs::write(&dest_path, generated).unwrap();

    println!("cargo:rerun-if-changed=docs/");
    println!("cargo:rerun-if-changed=build.rs");
}

fn extract_name_from_md(path: &Path) -> String {
    if let Ok(content) = fs::read_to_string(path) {
        if let Some(first_line) = content.lines().next() {
            let line = first_line.trim_start_matches('#').trim();
            if let Some(paren_pos) = line.rfind('(') {
                return line[..paren_pos].trim().to_string();
            }
            return line.to_string();
        }
    }
    String::new()
}

fn extract_diagnostic_codes(code_rs: &Path) -> HashSet<String> {
    let mut codes = HashSet::new();

    if let Ok(content) = fs::read_to_string(code_rs) {
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("//") || trimmed.is_empty() {
                continue;
            }
            if let Some(comma_pos) = trimmed.find(',') {
                let variant = &trimmed[..comma_pos];
                if variant.chars().next().map(|c| c.is_ascii_uppercase()).unwrap_or(false)
                    && variant.chars().all(|c| c.is_ascii_alphanumeric())
                {
                    codes.insert(variant.to_string());
                }
            }
        }
    }

    codes
}
