use expect_test::{expect, Expect};
use lexer::sdbl::tokenize_sdbl;

const CORPUS: &str = include_str!("fixtures/sdbl_golden_corpus.txt");

#[test]
fn golden_corpus() {
    let actual = render_corpus(CORPUS);
    let expected: Expect = expect![[r##"
        ---- 001 empty input

        ---- 002 whitespace only
          Whitespace @0 "   \t "
          Newline @5 "\n"

        ---- 003 newline only
          Newline @0 "\n"

        ---- 004 line comment
          Comment @0 "// comment line"
          Newline @15 "\n"

        ---- 005 ascii select with dot path
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Ident @7 "Name"
          Whitespace @11 " "
          KwFrom @12 "FROM"
          Whitespace @16 " "
          MdoCatalog @17 "Catalog"
          Dot @24 "."
          Ident @25 "Products"
          Newline @33 "\n"

        ---- 006 cyrillic select with dot path
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Ident @15 "Наименование"
          Whitespace @39 " "
          KwFrom @40 "ИЗ"
          Whitespace @44 " "
          MdoCatalog @45 "Справочник"
          Dot @65 "."
          Ident @66 "Товары"
          Newline @78 "\n"

        ---- 007 mixed case keywords
          KwSelect @0 "Select"
          Whitespace @6 " "
          Ident @7 "A"
          Whitespace @8 " "
          KwFrom @9 "From"
          Whitespace @13 " "
          MdoDocument @14 "Document"
          Dot @22 "."
          Ident @23 "Line"
          Newline @27 "\n"

        ---- 008 integer and float literals
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "42"
          Comma @9 ","
          Whitespace @10 " "
          Float @11 "3.14"
          Newline @15 "\n"

        ---- 009 comparison operators
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "A"
          Whitespace @7 " "
          Eq @8 "="
          Whitespace @9 " "
          Ident @10 "B"
          Whitespace @11 " "
          OpOr @12 "OR"
          Whitespace @14 " "
          Ident @15 "C"
          Whitespace @16 " "
          Neq @17 "<>"
          Whitespace @19 " "
          Ident @20 "D"
          Whitespace @21 " "
          OpOr @22 "OR"
          Whitespace @24 " "
          Ident @25 "E"
          Whitespace @26 " "
          Le @27 "<="
          Whitespace @29 " "
          Ident @30 "F"
          Whitespace @31 " "
          OpOr @32 "OR"
          Whitespace @34 " "
          Ident @35 "G"
          Whitespace @36 " "
          Ge @37 ">="
          Whitespace @39 " "
          Ident @40 "H"
          Whitespace @41 " "
          OpOr @42 "OR"
          Whitespace @44 " "
          Ident @45 "I"
          Whitespace @46 " "
          Lt @47 "<"
          Whitespace @48 " "
          Ident @49 "J"
          Whitespace @50 " "
          OpOr @51 "OR"
          Whitespace @53 " "
          Ident @54 "K"
          Whitespace @55 " "
          Gt @56 ">"
          Whitespace @57 " "
          Ident @58 "L"
          Newline @59 "\n"

        ---- 010 arithmetic operators
          Ident @0 "A"
          Whitespace @1 " "
          Plus @2 "+"
          Whitespace @3 " "
          Ident @4 "B"
          Whitespace @5 " "
          Minus @6 "-"
          Whitespace @7 " "
          Ident @8 "C"
          Whitespace @9 " "
          Star @10 "*"
          Whitespace @11 " "
          Ident @12 "D"
          Whitespace @13 " "
          Slash @14 "/"
          Whitespace @15 " "
          Ident @16 "E"
          Whitespace @17 " "
          Percent @18 "%"
          Whitespace @19 " "
          Ident @20 "F"
          Newline @21 "\n"

        ---- 011 punctuation and parens
          LParen @0 "("
          Ident @1 "A"
          Comma @2 ","
          Whitespace @3 " "
          Ident @4 "B"
          Semicolon @5 ";"
          Whitespace @6 " "
          Ident @7 "C"
          Dot @8 "."
          Ident @9 "D"
          RParen @10 ")"
          Newline @11 "\n"

        ---- 012 simple string
          String @0 "\""
          String @1 "Hello World"
          String @12 "\""
          Newline @13 "\n"

        ---- 013 string with doubled-quote escape
          String @0 "\""
          String @4 "B"
          String @5 "\""
          Newline @6 "\n"

        ---- 014 multiline string with bar
          String @0 "\""
          String @1 "line1"
          String @7 "| line2"
          String @14 "\""
          Newline @15 "\n"

        ---- 015 unterminated string at eof
          String @0 "\""
          String @1 "no end"

        ---- 016 date 8-digit
          Date @0 "'20240101'"
          Newline @10 "\n"

        ---- 017 date 14-digit
          Date @0 "'20240101120000'"
          Newline @16 "\n"

        ---- 018 parameter ascii
          Parameter @0 "&StartDate"
          Newline @10 "\n"

        ---- 019 parameter cyrillic
          Parameter @0 "&Имя"
          Newline @7 "\n"

        ---- 020 temp-table marker with identifier
          KwInto @0 "INTO"
          Whitespace @4 " "
          Hash @5 "#"
          Ident @6 "TempTable"
          Newline @15 "\n"

        ---- 021 hash standalone
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Hash @7 "#"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          Ident @14 "T"
          Newline @15 "\n"

        ---- 022 ampersand bare
          Ampersand @0 "&"
          Newline @1 "\n"

        ---- 023 bar standalone
          Bar @0 "|"
          Newline @1 "\n"

        ---- 024 identifier leading underscore and digits
          Ident @0 "_priv_1"
          Newline @7 "\n"

        ---- 025 LEFT JOIN with ON russian
          KwLeft @0 "ЛЕВОЕ"
          Whitespace @10 " "
          KwJoin @11 "СОЕДИНЕНИЕ"
          Whitespace @31 " "
          Ident @32 "T"
          Whitespace @33 " "
          KwOnOrBy @34 "ПО"
          Whitespace @38 " "
          Ident @39 "A"
          Whitespace @40 " "
          Eq @41 "="
          Whitespace @42 " "
          Ident @43 "B"
          Newline @44 "\n"

        ---- 026 INNER RIGHT FULL OUTER JOIN keywords
          KwInner @0 "INNER"
          Whitespace @5 " "
          KwRight @6 "RIGHT"
          Whitespace @11 " "
          KwFull @12 "FULL"
          Whitespace @16 " "
          KwOuter @17 "OUTER"
          Whitespace @22 " "
          KwJoin @23 "JOIN"
          Newline @27 "\n"

        ---- 027 GROUP BY HAVING
          KwGroup @0 "GROUP"
          Whitespace @5 " "
          KwOnOrBy @6 "BY"
          Whitespace @8 " "
          Ident @9 "Cat"
          Whitespace @12 " "
          KwHaving @13 "HAVING"
          Whitespace @19 " "
          FnCount @20 "COUNT"
          LParen @25 "("
          Star @26 "*"
          RParen @27 ")"
          Whitespace @28 " "
          Gt @29 ">"
          Whitespace @30 " "
          Decimal @31 "5"
          Newline @32 "\n"

        ---- 028 ORDER BY ASC DESC HIERARCHY
          KwOrder @0 "ORDER"
          Whitespace @5 " "
          KwOnOrBy @6 "BY"
          Whitespace @8 " "
          Ident @9 "Name"
          Whitespace @13 " "
          KwAsc @14 "ASC"
          Comma @17 ","
          Whitespace @18 " "
          Ident @19 "Price"
          Whitespace @24 " "
          KwDesc @25 "DESC"
          Whitespace @29 " "
          KwHierarchy @30 "HIERARCHY"
          Newline @39 "\n"

        ---- 029 UNION ALL subqueries
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwUnion @9 "UNION"
          Whitespace @14 " "
          KwAll @15 "ALL"
          Whitespace @18 " "
          KwSelect @19 "SELECT"
          Whitespace @25 " "
          Decimal @26 "2"
          Newline @27 "\n"

        ---- 030 DISTINCT TOP literal
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          KwDistinct @7 "DISTINCT"
          Whitespace @15 " "
          KwTop @16 "TOP"
          Whitespace @19 " "
          Decimal @20 "100"
          Whitespace @23 " "
          Ident @24 "Name"
          Newline @28 "\n"

        ---- 031 BETWEEN AND predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "P"
          Whitespace @7 " "
          KwBetween @8 "BETWEEN"
          Whitespace @15 " "
          Decimal @16 "1"
          Whitespace @17 " "
          OpAnd @18 "AND"
          Whitespace @21 " "
          Decimal @22 "10"
          Newline @24 "\n"

        ---- 032 LIKE ESCAPE predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "N"
          Whitespace @7 " "
          KwLike @8 "LIKE"
          Whitespace @12 " "
          String @13 "\""
          String @14 "%X%"
          String @17 "\""
          Whitespace @18 " "
          KwEscape @19 "ESCAPE"
          Whitespace @25 " "
          String @26 "\""
          String @27 "!"
          String @28 "\""
          Newline @29 "\n"

        ---- 033 IS NULL predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "X"
          Whitespace @7 " "
          KwIs @8 "IS"
          Whitespace @10 " "
          LitNull @11 "NULL"
          Newline @15 "\n"

        ---- 034 CASE WHEN THEN ELSE END
          KwCase @0 "CASE"
          Whitespace @4 " "
          KwWhen @5 "WHEN"
          Whitespace @9 " "
          Ident @10 "X"
          Whitespace @11 " "
          Gt @12 ">"
          Whitespace @13 " "
          Decimal @14 "0"
          Whitespace @15 " "
          KwThen @16 "THEN"
          Whitespace @20 " "
          Decimal @21 "1"
          Whitespace @22 " "
          KwElse @23 "ELSE"
          Whitespace @27 " "
          Decimal @28 "0"
          Whitespace @29 " "
          KwEnd @30 "END"
          Newline @33 "\n"

        ---- 035 CAST AS NUMBER
          KwCast @0 "CAST"
          LParen @4 "("
          Ident @5 "P"
          Whitespace @6 " "
          KwAs @7 "AS"
          Whitespace @9 " "
          TypeNumber @10 "NUMBER"
          LParen @16 "("
          Decimal @17 "15"
          Comma @19 ","
          Whitespace @20 " "
          Decimal @21 "2"
          RParen @22 ")"
          RParen @23 ")"
          Newline @24 "\n"

        ---- 036 REFS predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "R"
          Whitespace @7 " "
          KwRefs @8 "REFS"
          Whitespace @12 " "
          MdoCatalog @13 "Catalog"
          Dot @20 "."
          Ident @21 "Products"
          Newline @29 "\n"

        ---- 037 IN predicate with parameter
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "C"
          Whitespace @7 " "
          KwIn @8 "IN"
          Whitespace @10 " "
          LParen @11 "("
          Parameter @12 "&List"
          RParen @17 ")"
          Newline @18 "\n"

        ---- 038 INTO temp and DROP russian
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwInto @9 "ПОМЕСТИТЬ"
          Whitespace @27 " "
          Hash @28 "#"
          Ident @29 "T"
          Semicolon @30 ";"
          Whitespace @31 " "
          KwDrop @32 "УНИЧТОЖИТЬ"
          Whitespace @52 " "
          Hash @53 "#"
          Ident @54 "T"
          Newline @55 "\n"

        ---- 039 FOR UPDATE INDEX BY ONLY ALLOWED OVERALL
          KwFor @0 "FOR"
          Whitespace @3 " "
          KwUpdate @4 "UPDATE"
          Whitespace @10 " "
          KwIndex @11 "INDEX"
          Whitespace @16 " "
          KwOnOrBy @17 "BY"
          Whitespace @19 " "
          Ident @20 "T"
          Dot @21 "."
          Ident @22 "F"
          Whitespace @23 " "
          KwOnly @24 "ONLY"
          Whitespace @28 " "
          KwAllowed @29 "ALLOWED"
          Whitespace @36 " "
          KwOverall @37 "OVERALL"
          Newline @44 "\n"

        ---- 040 TOTALS AUTOORDER PERIODS russian
          KwTotals @0 "ИТОГИ"
          Whitespace @10 " "
          FnSum @11 "СУММА"
          LParen @21 "("
          Ident @22 "X"
          RParen @23 ")"
          Whitespace @24 " "
          KwOnOrBy @25 "ПО"
          Whitespace @29 " "
          KwOverall @30 "ОБЩИЕ"
          Whitespace @40 " "
          KwAutoOrder @41 "АВТОУПОРЯДОЧИВАНИЕ"
          Whitespace @77 " "
          KwPeriods @78 "ПЕРИОДАМИ"
          LParen @96 "("
          FnDay @97 "ДЕНЬ"
          Comma @105 ","
          Whitespace @106 " "
          FnDateTime @107 "ДАТАВРЕМЯ"
          LParen @125 "("
          Decimal @126 "2024"
          Comma @130 ","
          Whitespace @131 " "
          Decimal @132 "1"
          Comma @133 ","
          Whitespace @134 " "
          Decimal @135 "1"
          RParen @136 ")"
          Comma @137 ","
          Whitespace @138 " "
          Parameter @139 "&End"
          RParen @143 ")"
          Newline @144 "\n"

        ---- 041 aggregate functions
          FnSum @0 "SUM"
          LParen @3 "("
          Ident @4 "A"
          RParen @5 ")"
          Whitespace @6 " "
          FnAvg @7 "AVG"
          LParen @10 "("
          Ident @11 "B"
          RParen @12 ")"
          Whitespace @13 " "
          FnMin @14 "MIN"
          LParen @17 "("
          Ident @18 "C"
          RParen @19 ")"
          Whitespace @20 " "
          FnMax @21 "MAX"
          LParen @24 "("
          Ident @25 "D"
          RParen @26 ")"
          Whitespace @27 " "
          FnCount @28 "COUNT"
          LParen @33 "("
          Star @34 "*"
          RParen @35 ")"
          Newline @36 "\n"

        ---- 042 date functions
          FnYear @0 "YEAR"
          LParen @4 "("
          Ident @5 "D"
          RParen @6 ")"
          Whitespace @7 " "
          FnQuarter @8 "QUARTER"
          LParen @15 "("
          Ident @16 "D"
          RParen @17 ")"
          Whitespace @18 " "
          FnMonth @19 "MONTH"
          LParen @24 "("
          Ident @25 "D"
          RParen @26 ")"
          Whitespace @27 " "
          FnWeek @28 "WEEK"
          LParen @32 "("
          Ident @33 "D"
          RParen @34 ")"
          Whitespace @35 " "
          FnDay @36 "DAY"
          LParen @39 "("
          Ident @40 "D"
          RParen @41 ")"
          Whitespace @42 " "
          FnHour @43 "HOUR"
          LParen @47 "("
          Ident @48 "D"
          RParen @49 ")"
          Whitespace @50 " "
          FnMinute @51 "MINUTE"
          LParen @57 "("
          Ident @58 "D"
          RParen @59 ")"
          Whitespace @60 " "
          FnSecond @61 "SECOND"
          LParen @67 "("
          Ident @68 "D"
          RParen @69 ")"
          Whitespace @70 " "
          FnWeekDay @71 "WEEKDAY"
          LParen @78 "("
          Ident @79 "D"
          RParen @80 ")"
          Whitespace @81 " "
          FnDayOfYear @82 "DAYOFYEAR"
          LParen @91 "("
          Ident @92 "D"
          RParen @93 ")"
          Newline @94 "\n"

        ---- 043 date arithmetic functions
          FnDateAdd @0 "DATEADD"
          LParen @7 "("
          Ident @8 "D"
          Comma @9 ","
          Whitespace @10 " "
          FnYear @11 "YEAR"
          Comma @15 ","
          Whitespace @16 " "
          Decimal @17 "1"
          RParen @18 ")"
          Whitespace @19 " "
          FnDateDiff @20 "DATEDIFF"
          LParen @28 "("
          Ident @29 "D1"
          Comma @31 ","
          Whitespace @32 " "
          Ident @33 "D2"
          Comma @35 ","
          Whitespace @36 " "
          FnDay @37 "DAY"
          RParen @40 ")"
          Whitespace @41 " "
          FnBeginOfPeriod @42 "BEGINOFPERIOD"
          LParen @55 "("
          Ident @56 "D"
          Comma @57 ","
          Whitespace @58 " "
          FnQuarter @59 "QUARTER"
          RParen @66 ")"
          Whitespace @67 " "
          FnEndOfPeriod @68 "ENDOFPERIOD"
          LParen @79 "("
          Ident @80 "D"
          Comma @81 ","
          Whitespace @82 " "
          FnMonth @83 "MONTH"
          RParen @88 ")"
          Newline @89 "\n"

        ---- 044 string functions
          FnSubstring @0 "SUBSTRING"
          LParen @9 "("
          Ident @10 "S"
          Comma @11 ","
          Whitespace @12 " "
          Decimal @13 "1"
          Comma @14 ","
          Whitespace @15 " "
          Decimal @16 "10"
          RParen @18 ")"
          Whitespace @19 " "
          FnStringLength @20 "STRINGLENGTH"
          LParen @32 "("
          Ident @33 "S"
          RParen @34 ")"
          Whitespace @35 " "
          FnStrFind @36 "STRFIND"
          LParen @43 "("
          Ident @44 "S"
          Comma @45 ","
          Whitespace @46 " "
          String @47 "\""
          String @48 "x"
          String @49 "\""
          RParen @50 ")"
          Whitespace @51 " "
          FnUpper @52 "UPPER"
          LParen @57 "("
          Ident @58 "S"
          RParen @59 ")"
          Whitespace @60 " "
          FnLower @61 "LOWER"
          LParen @66 "("
          Ident @67 "S"
          RParen @68 ")"
          Whitespace @69 " "
          FnTrimAll @70 "TRIMALL"
          LParen @77 "("
          Ident @78 "S"
          RParen @79 ")"
          Whitespace @80 " "
          FnTrimL @81 "TRIML"
          LParen @86 "("
          Ident @87 "S"
          RParen @88 ")"
          Whitespace @89 " "
          FnTrimR @90 "TRIMR"
          LParen @95 "("
          Ident @96 "S"
          RParen @97 ")"
          Newline @98 "\n"

        ---- 045 math functions
          FnRound @0 "ROUND"
          LParen @5 "("
          Ident @6 "X"
          RParen @7 ")"
          Whitespace @8 " "
          FnInt @9 "INT"
          LParen @12 "("
          Ident @13 "X"
          RParen @14 ")"
          Whitespace @15 " "
          FnLog @16 "LOG"
          LParen @19 "("
          Ident @20 "X"
          RParen @21 ")"
          Whitespace @22 " "
          FnLog10 @23 "LOG10"
          LParen @28 "("
          Ident @29 "X"
          RParen @30 ")"
          Whitespace @31 " "
          FnPow @32 "POW"
          LParen @35 "("
          Ident @36 "X"
          Comma @37 ","
          Whitespace @38 " "
          Decimal @39 "2"
          RParen @40 ")"
          Whitespace @41 " "
          FnSqrt @42 "SQRT"
          LParen @46 "("
          Ident @47 "X"
          RParen @48 ")"
          Newline @49 "\n"

        ---- 046 type and null functions
          FnValueType @0 "VALUETYPE"
          LParen @9 "("
          Ident @10 "X"
          RParen @11 ")"
          Whitespace @12 " "
          FnPresentation @13 "PRESENTATION"
          LParen @25 "("
          Ident @26 "X"
          RParen @27 ")"
          Whitespace @28 " "
          FnRefPresentation @29 "REFPRESENTATION"
          LParen @44 "("
          Ident @45 "X"
          RParen @46 ")"
          Whitespace @47 " "
          FnIsNull @48 "ISNULL"
          LParen @54 "("
          Ident @55 "X"
          Comma @56 ","
          Whitespace @57 " "
          Decimal @58 "0"
          RParen @59 ")"
          Whitespace @60 " "
          FnEmptyTable @61 "EMPTYTABLE"
          Whitespace @71 " "
          FnEmptyRef @72 "EMPTYREF"
          Whitespace @80 " "
          FnUUID @81 "UUID"
          Newline @85 "\n"

        ---- 047 metadata objects dot paths
          MdoCatalog @0 "Catalog"
          Dot @7 "."
          Ident @8 "C"
          Whitespace @9 " "
          MdoDocument @10 "Document"
          Dot @18 "."
          Ident @19 "D"
          Whitespace @20 " "
          MdoInformationRegister @21 "InformationRegister"
          Dot @40 "."
          Ident @41 "I"
          Whitespace @42 " "
          MdoAccumulationRegister @43 "AccumulationRegister"
          Dot @63 "."
          Ident @64 "A"
          Whitespace @65 " "
          MdoAccountingRegister @66 "AccountingRegister"
          Dot @84 "."
          Ident @85 "R"
          Whitespace @86 " "
          MdoCalculationRegister @87 "CalculationRegister"
          Dot @106 "."
          Ident @107 "CR"
          Whitespace @109 " "
          MdoChartOfAccounts @110 "ChartOfAccounts"
          Dot @125 "."
          Ident @126 "COA"
          Whitespace @129 " "
          MdoChartOfCalculationTypes @130 "ChartOfCalculationTypes"
          Dot @153 "."
          Ident @154 "CCT"
          Whitespace @157 " "
          MdoChartOfCharacteristicTypes @158 "ChartOfCharacteristicTypes"
          Dot @184 "."
          Ident @185 "CCH"
          Whitespace @188 " "
          MdoEnum @189 "Enum"
          Dot @193 "."
          Ident @194 "E"
          Whitespace @195 " "
          MdoBusinessProcess @196 "BusinessProcess"
          Dot @211 "."
          Ident @212 "BP"
          Whitespace @214 " "
          MdoTask @215 "Task"
          Dot @219 "."
          Ident @220 "T"
          Whitespace @221 " "
          MdoConstant @222 "Constant"
          Dot @230 "."
          Ident @231 "K"
          Whitespace @232 " "
          MdoSequence @233 "Sequence"
          Dot @241 "."
          Ident @242 "S"
          Whitespace @243 " "
          MdoExternalDataSource @244 "ExternalDataSource"
          Dot @262 "."
          Ident @263 "X"
          Newline @264 "\n"

        ---- 048 virtual tables
          MdoAccumulationRegister @0 "AccumulationRegister"
          Dot @20 "."
          Ident @21 "Stock"
          Dot @26 "."
          VtBalance @27 "Balance"
          Whitespace @34 " "
          MdoAccumulationRegister @35 "AccumulationRegister"
          Dot @55 "."
          Ident @56 "Stock"
          Dot @61 "."
          VtTurnovers @62 "Turnovers"
          Whitespace @71 " "
          MdoAccumulationRegister @72 "AccumulationRegister"
          Dot @92 "."
          Ident @93 "Stock"
          Dot @98 "."
          VtBalanceAndTurnovers @99 "BalanceAndTurnovers"
          Whitespace @118 " "
          MdoInformationRegister @119 "InformationRegister"
          Dot @138 "."
          Ident @139 "Prices"
          Dot @145 "."
          VtSliceLast @146 "SliceLast"
          Whitespace @155 " "
          MdoInformationRegister @156 "InformationRegister"
          Dot @175 "."
          Ident @176 "Prices"
          Dot @182 "."
          VtSliceFirst @183 "SliceFirst"
          Whitespace @193 " "
          MdoAccountingRegister @194 "AccountingRegister"
          Dot @212 "."
          Ident @213 "Main"
          Dot @217 "."
          VtDrCrTurnovers @218 "DrCrTurnovers"
          Newline @231 "\n"

        ---- 049 type literals and bool and null literals
          KwType @0 "TYPE"
          LParen @4 "("
          TypeBoolean @5 "Boolean"
          RParen @12 ")"
          Whitespace @13 " "
          KwType @14 "TYPE"
          LParen @18 "("
          TypeNumber @19 "Number"
          RParen @25 ")"
          Whitespace @26 " "
          KwType @27 "TYPE"
          LParen @31 "("
          TypeString @32 "String"
          RParen @38 ")"
          Whitespace @39 " "
          KwType @40 "TYPE"
          LParen @44 "("
          TypeDate @45 "Date"
          RParen @49 ")"
          Whitespace @50 " "
          LitTrue @51 "TRUE"
          Whitespace @55 " "
          LitFalse @56 "FALSE"
          Whitespace @61 " "
          LitTrue @62 "ИСТИНА"
          Whitespace @74 " "
          LitFalse @75 "ЛОЖЬ"
          Whitespace @83 " "
          LitNull @84 "NULL"
          Whitespace @88 " "
          LitUndefined @89 "Неопределено"
          Whitespace @113 " "
          KwValue @114 "VALUE"
          LParen @119 "("
          MdoEnum @120 "Enum"
          Dot @124 "."
          Ident @125 "Status"
          Dot @131 "."
          Ident @132 "Done"
          RParen @136 ")"
          Newline @137 "\n"

        ---- 050 logical operators and period types
          Ident @0 "A"
          Whitespace @1 " "
          OpAnd @2 "AND"
          Whitespace @5 " "
          Ident @6 "B"
          Whitespace @7 " "
          OpOr @8 "OR"
          Whitespace @10 " "
          OpNot @11 "NOT"
          Whitespace @14 " "
          Ident @15 "C"
          Semicolon @16 ";"
          Whitespace @17 " "
          PeriodTenDays @18 "ДЕКАДА"
          Whitespace @30 " "
          PeriodHalfYear @31 "ПОЛУГОДИЕ"
          Newline @49 "\n"

        ---- 051 russian alias keyword
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Ident @15 "П"
          Dot @17 "."
          Ident @18 "Наименование"
          Whitespace @42 " "
          KwAs @43 "КАК"
          Whitespace @49 " "
          Ident @50 "Наименование"
          Whitespace @74 " "
          KwFrom @75 "ИЗ"
          Whitespace @79 " "
          MdoCatalog @80 "Справочник"
          Dot @100 "."
          Ident @101 "Продукты"
          Whitespace @117 " "
          KwAs @118 "КАК"
          Whitespace @124 " "
          Ident @125 "П"
          Newline @127 "\n"

        ---- 052 english join on
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Ident @7 "t1"
          Dot @9 "."
          Ident @10 "id"
          Whitespace @12 " "
          KwFrom @13 "FROM"
          Whitespace @17 " "
          MdoCatalog @18 "Catalog"
          Dot @25 "."
          Ident @26 "Products"
          Whitespace @34 " "
          KwAs @35 "AS"
          Whitespace @37 " "
          Ident @38 "t1"
          Whitespace @40 " "
          KwInner @41 "INNER"
          Whitespace @46 " "
          KwJoin @47 "JOIN"
          Whitespace @51 " "
          MdoCatalog @52 "Catalog"
          Dot @59 "."
          Ident @60 "Prices"
          Whitespace @66 " "
          KwAs @67 "AS"
          Whitespace @69 " "
          Ident @70 "t2"
          Whitespace @72 " "
          KwOnOrBy @73 "ON"
          Whitespace @75 " "
          Ident @76 "t2"
          Dot @78 "."
          Ident @79 "product"
          Whitespace @86 " "
          Eq @87 "="
          Whitespace @88 " "
          Ident @89 "t1"
          Dot @91 "."
          Ident @92 "ref"
          Newline @95 "\n"

        ---- 053 russian clause keywords
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          KwDistinct @15 "РАЗЛИЧНЫЕ"
          Whitespace @33 " "
          KwTop @34 "ПЕРВЫЕ"
          Whitespace @46 " "
          Decimal @47 "5"
          Whitespace @48 " "
          Ident @49 "Имя"
          Whitespace @55 " "
          KwWhere @56 "ГДЕ"
          Whitespace @62 " "
          Ident @63 "X"
          Whitespace @64 " "
          Gt @65 ">"
          Whitespace @66 " "
          Decimal @67 "0"
          Whitespace @68 " "
          KwGroup @69 "СГРУППИРОВАТЬ"
          Whitespace @95 " "
          KwOnOrBy @96 "ПО"
          Whitespace @100 " "
          Ident @101 "Y"
          Whitespace @102 " "
          KwHaving @103 "ИМЕЮЩИЕ"
          Whitespace @117 " "
          FnSum @118 "СУММА"
          LParen @128 "("
          Ident @129 "Y"
          RParen @130 ")"
          Whitespace @131 " "
          Gt @132 ">"
          Whitespace @133 " "
          Decimal @134 "0"
          Whitespace @135 " "
          KwOrder @136 "УПОРЯДОЧИТЬ"
          Whitespace @158 " "
          KwOnOrBy @159 "ПО"
          Whitespace @163 " "
          Ident @164 "Y"
          Whitespace @165 " "
          KwUnion @166 "ОБЪЕДИНИТЬ"
          Whitespace @186 " "
          KwAll @187 "ВСЕ"
          Whitespace @193 " "
          KwSelect @194 "ВЫБРАТЬ"
          Whitespace @208 " "
          Decimal @209 "2"
          Newline @210 "\n"

        ---- 054 russian predicates and case
          KwWhere @0 "ГДЕ"
          Whitespace @6 " "
          Ident @7 "X"
          Whitespace @8 " "
          KwBetween @9 "МЕЖДУ"
          Whitespace @19 " "
          Decimal @20 "1"
          Whitespace @21 " "
          OpAnd @22 "И"
          Whitespace @24 " "
          Decimal @25 "10"
          Whitespace @27 " "
          OpOr @28 "ИЛИ"
          Whitespace @34 " "
          OpNot @35 "НЕ"
          Whitespace @39 " "
          Ident @40 "Y"
          Whitespace @41 " "
          KwIs @42 "ЕСТЬ"
          Whitespace @50 " "
          LitNull @51 "NULL"
          Whitespace @55 " "
          OpAnd @56 "И"
          Whitespace @58 " "
          Ident @59 "Z"
          Whitespace @60 " "
          KwLike @61 "ПОДОБНО"
          Whitespace @75 " "
          String @76 "\""
          String @77 "%x%"
          String @80 "\""
          Whitespace @81 " "
          OpAnd @82 "И"
          Whitespace @84 " "
          Ident @85 "W"
          Whitespace @86 " "
          KwIn @87 "В"
          Whitespace @89 " "
          LParen @90 "("
          Parameter @91 "&P"
          RParen @93 ")"
          Whitespace @94 " "
          KwCase @95 "ВЫБОР"
          Whitespace @105 " "
          KwWhen @106 "КОГДА"
          Whitespace @116 " "
          Ident @117 "A"
          Whitespace @118 " "
          Gt @119 ">"
          Whitespace @120 " "
          Decimal @121 "0"
          Whitespace @122 " "
          KwThen @123 "ТОГДА"
          Whitespace @133 " "
          Decimal @134 "1"
          Whitespace @135 " "
          KwElse @136 "ИНАЧЕ"
          Whitespace @146 " "
          Decimal @147 "0"
          Whitespace @148 " "
          KwEnd @149 "КОНЕЦ"
          Newline @159 "\n"

        ---- 055 english totals
          KwTotals @0 "TOTALS"
          Whitespace @6 " "
          FnSum @7 "SUM"
          LParen @10 "("
          Ident @11 "X"
          RParen @12 ")"
          Newline @13 "\n"

        ---- 056 russian join family
          KwInner @0 "ВНУТРЕННЕЕ"
          Whitespace @20 " "
          KwRight @21 "ПРАВОЕ"
          Whitespace @33 " "
          KwFull @34 "ПОЛНОЕ"
          Whitespace @46 " "
          KwOuter @47 "ВНЕШНЕЕ"
          Whitespace @61 " "
          KwJoin @62 "СОЕДИНЕНИЕ"
          Newline @82 "\n"

        ---- 057 english left join
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          Ident @14 "T"
          Whitespace @15 " "
          KwLeft @16 "LEFT"
          Whitespace @20 " "
          KwJoin @21 "JOIN"
          Whitespace @25 " "
          Ident @26 "U"
          Whitespace @27 " "
          KwOnOrBy @28 "ON"
          Whitespace @30 " "
          Ident @31 "T"
          Dot @32 "."
          Ident @33 "id"
          Whitespace @35 " "
          Eq @36 "="
          Whitespace @37 " "
          Ident @38 "U"
          Dot @39 "."
          Ident @40 "id"
          Newline @42 "\n"

        ---- 058 slice2-addendum order-by direction russian
          KwOrder @0 "УПОРЯДОЧИТЬ"
          Whitespace @22 " "
          KwOnOrBy @23 "ПО"
          Whitespace @27 " "
          Ident @28 "Имя"
          Whitespace @34 " "
          KwAsc @35 "ВОЗР"
          Comma @43 ","
          Whitespace @44 " "
          Ident @45 "Цена"
          Whitespace @53 " "
          KwDesc @54 "УБЫВ"
          Whitespace @62 " "
          KwHierarchy @63 "ИЕРАРХИЯ"
          Newline @79 "\n"

        ---- 059 slice2-addendum select-prefix qualifier russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          KwAllowed @15 "РАЗРЕШЕННЫЕ"
          Whitespace @37 " "
          Ident @38 "Имя"
          Whitespace @44 " "
          KwFrom @45 "ИЗ"
          Whitespace @49 " "
          MdoCatalog @50 "Справочник"
          Dot @70 "."
          Ident @71 "Товары"
          Newline @83 "\n"

        ---- 060 slice2-addendum for update russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          Ident @22 "T"
          Whitespace @23 " "
          KwFor @24 "ДЛЯ"
          Whitespace @30 " "
          KwUpdate @31 "ИЗМЕНЕНИЯ"
          Newline @49 "\n"

        ---- 061 slice2-addendum index by russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwIndex @17 "ИНДЕКСИРОВАТЬ"
          Whitespace @43 " "
          KwOnOrBy @44 "ПО"
          Whitespace @48 " "
          Ident @49 "T"
          Dot @50 "."
          Ident @51 "F"
          Newline @52 "\n"

        ---- 062 slice2-addendum totals only-hierarchy russian
          KwTotals @0 "ИТОГИ"
          Whitespace @10 " "
          FnSum @11 "СУММА"
          LParen @21 "("
          Ident @22 "X"
          RParen @23 ")"
          Whitespace @24 " "
          KwOnOrBy @25 "ПО"
          Whitespace @29 " "
          Ident @30 "Номенклатура"
          Whitespace @54 " "
          KwOnly @55 "ТОЛЬКО"
          Whitespace @67 " "
          KwHierarchy @68 "ИЕРАРХИЯ"
          Newline @84 "\n"

        ---- 063 slice2-addendum like escape russian
          KwWhere @0 "ГДЕ"
          Whitespace @6 " "
          Ident @7 "Н"
          Whitespace @9 " "
          KwLike @10 "ПОДОБНО"
          Whitespace @24 " "
          String @25 "\""
          String @26 "%X%"
          String @29 "\""
          Whitespace @30 " "
          KwEscape @31 "СПЕЦСИМВОЛ"
          Whitespace @51 " "
          String @52 "\""
          String @53 "!"
          String @54 "\""
          Newline @55 "\n"

        ---- 064 slice2-addendum refs russian
          KwWhere @0 "ГДЕ"
          Whitespace @6 " "
          Ident @7 "Р"
          Whitespace @9 " "
          KwRefs @10 "ССЫЛКА"
          Whitespace @22 " "
          MdoDocument @23 "Документ"
          Dot @39 "."
          Ident @40 "ПриходнаяНакладная"
          Newline @76 "\n"

        ---- 065 slice2-addendum cast russian
          KwCast @0 "ВЫРАЗИТЬ"
          LParen @16 "("
          Ident @17 "П"
          Whitespace @19 " "
          KwAs @20 "КАК"
          Whitespace @26 " "
          TypeNumber @27 "ЧИСЛО"
          LParen @37 "("
          Decimal @38 "15"
          Comma @40 ","
          Whitespace @41 " "
          Decimal @42 "2"
          RParen @43 ")"
          RParen @44 ")"
          Newline @45 "\n"

        ---- 066 slice2-addendum type russian
          KwType @0 "ТИП"
          LParen @6 "("
          TypeNumber @7 "Число"
          RParen @17 ")"
          Newline @18 "\n"

        ---- 067 slice2-addendum value russian
          KwValue @0 "ЗНАЧЕНИЕ"
          LParen @16 "("
          MdoEnum @17 "Перечисление"
          Dot @41 "."
          Ident @42 "Статус"
          Dot @54 "."
          Ident @55 "Готов"
          RParen @65 ")"
          Newline @66 "\n"

        ---- 068 slice2-addendum drop english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwInto @9 "INTO"
          Whitespace @13 " "
          Hash @14 "#"
          Ident @15 "T"
          Semicolon @16 ";"
          Whitespace @17 " "
          KwDrop @18 "DROP"
          Whitespace @22 " "
          Hash @23 "#"
          Ident @24 "T"
          Newline @25 "\n"

        ---- 069 slice2-addendum autoorder english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwOrder @9 "ORDER"
          Whitespace @14 " "
          KwOnOrBy @15 "BY"
          Whitespace @17 " "
          Ident @18 "F"
          Whitespace @19 " "
          KwAutoOrder @20 "AUTOORDER"
          Newline @29 "\n"

        ---- 070 slice2-addendum periods english
          KwTotals @0 "TOTALS"
          Whitespace @6 " "
          FnSum @7 "SUM"
          LParen @10 "("
          Ident @11 "X"
          RParen @12 ")"
          Whitespace @13 " "
          KwOnOrBy @14 "BY"
          Whitespace @16 " "
          KwOverall @17 "OVERALL"
          Whitespace @24 " "
          KwPeriods @25 "PERIODS"
          LParen @32 "("
          FnDay @33 "DAY"
          Comma @36 ","
          Whitespace @37 " "
          FnDateTime @38 "DATETIME"
          LParen @46 "("
          Decimal @47 "2024"
          Comma @51 ","
          Whitespace @52 " "
          Decimal @53 "1"
          Comma @54 ","
          Whitespace @55 " "
          Decimal @56 "1"
          RParen @57 ")"
          Comma @58 ","
          Whitespace @59 " "
          Parameter @60 "&End"
          RParen @64 ")"
          Newline @65 "\n"

        ---- 071 slice3a primitive types russian
          KwCast @0 "ВЫРАЗИТЬ"
          LParen @16 "("
          Ident @17 "X"
          Whitespace @18 " "
          KwAs @19 "КАК"
          Whitespace @25 " "
          TypeBoolean @26 "БУЛЕВО"
          RParen @38 ")"
          Whitespace @39 " "
          KwCast @40 "ВЫРАЗИТЬ"
          LParen @56 "("
          Ident @57 "Y"
          Whitespace @58 " "
          KwAs @59 "КАК"
          Whitespace @65 " "
          TypeString @66 "СТРОКА"
          LParen @78 "("
          Decimal @79 "50"
          RParen @81 ")"
          RParen @82 ")"
          Whitespace @83 " "
          KwCast @84 "ВЫРАЗИТЬ"
          LParen @100 "("
          Ident @101 "Z"
          Whitespace @102 " "
          KwAs @103 "КАК"
          Whitespace @109 " "
          TypeDate @110 "ДАТА"
          RParen @118 ")"
          Newline @119 "\n"

        ---- 072 slice3a undefined literal english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Star @7 "*"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          Ident @14 "T"
          Whitespace @15 " "
          KwWhere @16 "WHERE"
          Whitespace @21 " "
          Ident @22 "X"
          Whitespace @23 " "
          Eq @24 "="
          Whitespace @25 " "
          LitUndefined @26 "UNDEFINED"
          Whitespace @35 " "
          OpOr @36 "OR"
          Whitespace @38 " "
          Ident @39 "Y"
          Whitespace @40 " "
          Neq @41 "<>"
          Whitespace @43 " "
          LitUndefined @44 "UNDEFINED"
          Newline @53 "\n"

        ---- 073 slice3a period types english
          KwTotals @0 "TOTALS"
          Whitespace @6 " "
          FnSum @7 "SUM"
          LParen @10 "("
          Ident @11 "X"
          RParen @12 ")"
          Whitespace @13 " "
          KwOnOrBy @14 "BY"
          Whitespace @16 " "
          KwPeriods @17 "PERIODS"
          LParen @24 "("
          PeriodTenDays @25 "TENDAYS"
          Comma @32 ","
          Whitespace @33 " "
          Parameter @34 "&S"
          Comma @36 ","
          Whitespace @37 " "
          Parameter @38 "&E"
          RParen @40 ")"
          Comma @41 ","
          Whitespace @42 " "
          KwPeriods @43 "PERIODS"
          LParen @50 "("
          PeriodHalfYear @51 "HALFYEAR"
          Comma @59 ","
          Whitespace @60 " "
          Parameter @61 "&T"
          Comma @63 ","
          Whitespace @64 " "
          Parameter @65 "&U"
          RParen @67 ")"
          Newline @68 "\n"

        ---- 074 slice3b register roots russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoInformationRegister @22 "РегистрСведений"
          Dot @52 "."
          Ident @53 "Цены"
          Comma @61 ","
          Whitespace @62 " "
          MdoAccumulationRegister @63 "РегистрНакопления"
          Dot @97 "."
          Ident @98 "Товары"
          Comma @110 ","
          Whitespace @111 " "
          MdoAccountingRegister @112 "РегистрБухгалтерии"
          Dot @148 "."
          Ident @149 "Хозрасчетный"
          Comma @173 ","
          Whitespace @174 " "
          MdoCalculationRegister @175 "РегистрРасчета"
          Dot @203 "."
          Ident @204 "Начисления"
          Newline @224 "\n"

        ---- 075 slice3b chart roots russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoChartOfAccounts @22 "ПланСчетов"
          Dot @42 "."
          Ident @43 "Основной"
          Comma @59 ","
          Whitespace @60 " "
          MdoChartOfCalculationTypes @61 "ПланВидовРасчета"
          Dot @93 "."
          Ident @94 "Основные"
          Comma @110 ","
          Whitespace @111 " "
          MdoChartOfCharacteristicTypes @112 "ПланВидовХарактеристик"
          Dot @156 "."
          Ident @157 "Свойства"
          Newline @173 "\n"

        ---- 076 slice3b object roots russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoBusinessProcess @22 "БизнесПроцесс"
          Dot @48 "."
          Ident @49 "Согласование"
          Comma @73 ","
          Whitespace @74 " "
          MdoTask @75 "Задача"
          Dot @87 "."
          Ident @88 "Поручение"
          Comma @106 ","
          Whitespace @107 " "
          MdoConstant @108 "Константа"
          Dot @126 "."
          Ident @127 "Организация"
          Comma @149 ","
          Whitespace @150 " "
          MdoSequence @151 "Последовательность"
          Dot @187 "."
          Ident @188 "Проведение"
          Newline @208 "\n"

        ---- 077 slice3b document journal bilingual
          MdoDocumentJournal @0 "ЖурналДокументов"
          Dot @32 "."
          Ident @33 "Продажи"
          Whitespace @47 " "
          MdoDocumentJournal @48 "DocumentJournal"
          Dot @63 "."
          Ident @64 "Sales"
          Newline @69 "\n"

        ---- 078 slice3b exchange plan bilingual
          MdoExchangePlan @0 "ПланОбмена"
          Dot @20 "."
          Ident @21 "Филиалы"
          Whitespace @35 " "
          MdoExchangePlan @36 "ExchangePlan"
          Dot @48 "."
          Ident @49 "Branches"
          Newline @57 "\n"

        ---- 079 slice3b filter criterion bilingual
          MdoFilterCriterion @0 "КритерийОтбора"
          Dot @28 "."
          Ident @29 "Связанные"
          Whitespace @47 " "
          MdoFilterCriterion @48 "FilterCriterion"
          Dot @63 "."
          Ident @64 "Related"
          Newline @71 "\n"

        ---- 080 slice3b constants aggregate bilingual
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoConstants @22 "Константы"
          Semicolon @40 ";"
          Whitespace @41 " "
          KwSelect @42 "SELECT"
          Whitespace @48 " "
          Decimal @49 "1"
          Whitespace @50 " "
          KwFrom @51 "FROM"
          Whitespace @55 " "
          MdoConstants @56 "Constants"
          Newline @65 "\n"

        ---- 081 slice3b unmatched byte error fallback
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Error @15 "@"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          Ident @22 "Т"
          Newline @24 "\n"

        ---- 082 slice4 aggregate functions russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnSum @15 "СУММА"
          LParen @25 "("
          Ident @26 "Цена"
          RParen @34 ")"
          Comma @35 ","
          Whitespace @36 " "
          FnAvg @37 "СРЕДНЕЕ"
          LParen @51 "("
          Ident @52 "Цена"
          RParen @60 ")"
          Comma @61 ","
          Whitespace @62 " "
          FnMin @63 "МИНИМУМ"
          LParen @77 "("
          Ident @78 "Цена"
          RParen @86 ")"
          Comma @87 ","
          Whitespace @88 " "
          FnMax @89 "МАКСИМУМ"
          LParen @105 "("
          Ident @106 "Цена"
          RParen @114 ")"
          Comma @115 ","
          Whitespace @116 " "
          FnCount @117 "КОЛИЧЕСТВО"
          LParen @137 "("
          Star @138 "*"
          RParen @139 ")"
          Whitespace @140 " "
          KwFrom @141 "ИЗ"
          Whitespace @145 " "
          Ident @146 "Продажи"
          Newline @160 "\n"

        ---- 083 slice4 date part functions russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnYear @15 "ГОД"
          LParen @21 "("
          Ident @22 "Момент"
          RParen @34 ")"
          Comma @35 ","
          Whitespace @36 " "
          FnQuarter @37 "КВАРТАЛ"
          LParen @51 "("
          Ident @52 "Момент"
          RParen @64 ")"
          Comma @65 ","
          Whitespace @66 " "
          FnMonth @67 "МЕСЯЦ"
          LParen @77 "("
          Ident @78 "Момент"
          RParen @90 ")"
          Comma @91 ","
          Whitespace @92 " "
          FnDayOfYear @93 "ДЕНЬГОДА"
          LParen @109 "("
          Ident @110 "Момент"
          RParen @122 ")"
          Comma @123 ","
          Whitespace @124 " "
          FnDay @125 "ДЕНЬ"
          LParen @133 "("
          Ident @134 "Момент"
          RParen @146 ")"
          Comma @147 ","
          Whitespace @148 " "
          FnWeek @149 "НЕДЕЛЯ"
          LParen @161 "("
          Ident @162 "Момент"
          RParen @174 ")"
          Comma @175 ","
          Whitespace @176 " "
          FnWeekDay @177 "ДЕНЬНЕДЕЛИ"
          LParen @197 "("
          Ident @198 "Момент"
          RParen @210 ")"
          Comma @211 ","
          Whitespace @212 " "
          FnHour @213 "ЧАС"
          LParen @219 "("
          Ident @220 "Момент"
          RParen @232 ")"
          Comma @233 ","
          Whitespace @234 " "
          FnMinute @235 "МИНУТА"
          LParen @247 "("
          Ident @248 "Момент"
          RParen @260 ")"
          Comma @261 ","
          Whitespace @262 " "
          FnSecond @263 "СЕКУНДА"
          LParen @277 "("
          Ident @278 "Момент"
          RParen @290 ")"
          Newline @291 "\n"

        ---- 084 slice4 date arithmetic functions russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnBeginOfPeriod @15 "НАЧАЛОПЕРИОДА"
          LParen @41 "("
          Ident @42 "Момент"
          Comma @54 ","
          Whitespace @55 " "
          FnMonth @56 "МЕСЯЦ"
          RParen @66 ")"
          Comma @67 ","
          Whitespace @68 " "
          FnEndOfPeriod @69 "КОНЕЦПЕРИОДА"
          LParen @93 "("
          Ident @94 "Момент"
          Comma @106 ","
          Whitespace @107 " "
          FnYear @108 "ГОД"
          RParen @114 ")"
          Comma @115 ","
          Whitespace @116 " "
          FnDateAdd @117 "ДОБАВИТЬКДАТЕ"
          LParen @143 "("
          Ident @144 "Момент"
          Comma @156 ","
          Whitespace @157 " "
          FnDay @158 "ДЕНЬ"
          Comma @166 ","
          Whitespace @167 " "
          Decimal @168 "5"
          RParen @169 ")"
          Comma @170 ","
          Whitespace @171 " "
          FnDateDiff @172 "РАЗНОСТЬДАТ"
          LParen @194 "("
          Ident @195 "Момент"
          Comma @207 ","
          Whitespace @208 " "
          FnDateTime @209 "ДАТАВРЕМЯ"
          LParen @227 "("
          Decimal @228 "2024"
          Comma @232 ","
          Whitespace @233 " "
          Decimal @234 "1"
          Comma @235 ","
          Whitespace @236 " "
          Decimal @237 "1"
          RParen @238 ")"
          Comma @239 ","
          Whitespace @240 " "
          FnHour @241 "ЧАС"
          RParen @247 ")"
          Newline @248 "\n"

        ---- 085 slice4 string functions russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnSubstring @15 "ПОДСТРОКА"
          LParen @33 "("
          Ident @34 "Имя"
          Comma @40 ","
          Whitespace @41 " "
          Decimal @42 "1"
          Comma @43 ","
          Whitespace @44 " "
          Decimal @45 "5"
          RParen @46 ")"
          Comma @47 ","
          Whitespace @48 " "
          FnStringLength @49 "ДЛИНАСТРОКИ"
          LParen @71 "("
          Ident @72 "Имя"
          RParen @78 ")"
          Comma @79 ","
          Whitespace @80 " "
          FnStrFind @81 "СТРНАЙТИ"
          LParen @97 "("
          Ident @98 "Имя"
          Comma @104 ","
          Whitespace @105 " "
          String @106 "\""
          String @107 "к"
          String @109 "\""
          RParen @110 ")"
          Comma @111 ","
          Whitespace @112 " "
          FnUpper @113 "ВРЕГ"
          LParen @121 "("
          Ident @122 "Имя"
          RParen @128 ")"
          Comma @129 ","
          Whitespace @130 " "
          FnLower @131 "НРЕГ"
          LParen @139 "("
          Ident @140 "Имя"
          RParen @146 ")"
          Comma @147 ","
          Whitespace @148 " "
          FnTrimAll @149 "СОКРЛП"
          LParen @161 "("
          Ident @162 "Имя"
          RParen @168 ")"
          Comma @169 ","
          Whitespace @170 " "
          FnTrimL @171 "СОКРЛ"
          LParen @181 "("
          Ident @182 "Имя"
          RParen @188 ")"
          Comma @189 ","
          Whitespace @190 " "
          FnTrimR @191 "СОКРП"
          LParen @201 "("
          Ident @202 "Имя"
          RParen @208 ")"
          Newline @209 "\n"

        ---- 086 slice4 numeric type and null functions russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnRound @15 "ОКР"
          LParen @21 "("
          Ident @22 "Цена"
          Comma @30 ","
          Whitespace @31 " "
          Decimal @32 "2"
          RParen @33 ")"
          Comma @34 ","
          Whitespace @35 " "
          FnInt @36 "ЦЕЛ"
          LParen @42 "("
          Ident @43 "Цена"
          RParen @51 ")"
          Comma @52 ","
          Whitespace @53 " "
          FnValueType @54 "ТИПЗНАЧЕНИЯ"
          LParen @76 "("
          Ident @77 "Товар"
          RParen @87 ")"
          Comma @88 ","
          Whitespace @89 " "
          FnPresentation @90 "ПРЕДСТАВЛЕНИЕ"
          LParen @116 "("
          Ident @117 "Товар"
          RParen @127 ")"
          Comma @128 ","
          Whitespace @129 " "
          FnRefPresentation @130 "ПРЕДСТАВЛЕНИЕССЫЛКИ"
          LParen @168 "("
          Ident @169 "Товар"
          RParen @179 ")"
          Comma @180 ","
          Whitespace @181 " "
          FnIsNull @182 "ЕСТЬNULL"
          LParen @194 "("
          Ident @195 "Цена"
          Comma @203 ","
          Whitespace @204 " "
          Decimal @205 "0"
          RParen @206 ")"
          Comma @207 ","
          Whitespace @208 " "
          FnUUID @209 "УНИКАЛЬНЫЙИДЕНТИФИКАТОР"
          LParen @255 "("
          Ident @256 "Товар"
          RParen @266 ")"
          Newline @267 "\n"

        ---- 087 slice4 empty table keyword and empty ref selector russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnEmptyTable @15 "ПУСТАЯТАБЛИЦА"
          Dot @41 "."
          LParen @42 "("
          Ident @43 "Ном"
          Comma @49 ","
          Whitespace @50 " "
          Ident @51 "Тов"
          RParen @57 ")"
          Whitespace @58 " "
          KwAs @59 "КАК"
          Whitespace @65 " "
          Ident @66 "Состав"
          Whitespace @78 " "
          KwFrom @79 "ИЗ"
          Whitespace @83 " "
          MdoDocument @84 "Документ"
          Dot @100 "."
          Ident @101 "Расход"
          Whitespace @113 " "
          KwWhere @114 "ГДЕ"
          Whitespace @120 " "
          Ident @121 "Товар"
          Whitespace @131 " "
          Eq @132 "="
          Whitespace @133 " "
          KwValue @134 "ЗНАЧЕНИЕ"
          LParen @150 "("
          MdoCatalog @151 "Справочник"
          Dot @171 "."
          Ident @172 "Товары"
          Dot @184 "."
          FnEmptyRef @185 "ПустаяСсылка"
          RParen @209 ")"
          Newline @210 "\n"

        ---- 088 slice4 left and right substring russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnLeft @15 "ЛЕВ"
          LParen @21 "("
          Ident @22 "Имя"
          Comma @28 ","
          Whitespace @29 " "
          Decimal @30 "3"
          RParen @31 ")"
          Comma @32 ","
          Whitespace @33 " "
          FnRight @34 "ПРАВ"
          LParen @42 "("
          Ident @43 "Имя"
          Comma @49 ","
          Whitespace @50 " "
          Decimal @51 "3"
          RParen @52 ")"
          Whitespace @53 " "
          KwFrom @54 "ИЗ"
          Whitespace @58 " "
          MdoCatalog @59 "Справочник"
          Dot @79 "."
          Ident @80 "Товары"
          Newline @92 "\n"

        ---- 089 slice4 join keywords keep the english left and right
          KwLeft @0 "ЛЕВОЕ"
          Whitespace @10 " "
          KwJoin @11 "СОЕДИНЕНИЕ"
          Whitespace @31 " "
          KwRight @32 "ПРАВОЕ"
          Whitespace @44 " "
          KwJoin @45 "СОЕДИНЕНИЕ"
          Whitespace @65 " "
          KwLeft @66 "LEFT"
          Whitespace @70 " "
          KwJoin @71 "JOIN"
          Whitespace @75 " "
          KwRight @76 "RIGHT"
          Whitespace @81 " "
          KwJoin @82 "JOIN"
          Newline @86 "\n"

        ---- 090 slice4 string replacement bilingual
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnStrReplace @15 "СтрЗаменить"
          LParen @37 "("
          Ident @38 "Имя"
          Comma @44 ","
          Whitespace @45 " "
          String @46 "\""
          String @47 "к"
          String @49 "\""
          Comma @50 ","
          Whitespace @51 " "
          String @52 "\""
          String @53 "г"
          String @55 "\""
          RParen @56 ")"
          Semicolon @57 ";"
          Whitespace @58 " "
          KwSelect @59 "SELECT"
          Whitespace @65 " "
          FnStrReplace @66 "StrReplace"
          LParen @76 "("
          Ident @77 "Name"
          Comma @81 ","
          Whitespace @82 " "
          String @83 "\""
          String @84 "k"
          String @85 "\""
          Comma @86 ","
          Whitespace @87 " "
          String @88 "\""
          String @89 "g"
          String @90 "\""
          RParen @91 ")"
          Newline @92 "\n"

        ---- 091 slice4 record autonumber bilingual
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnRecordAutoNumber @15 "АВТОНОМЕРЗАПИСИ"
          LParen @45 "("
          RParen @46 ")"
          Whitespace @47 " "
          KwInto @48 "ПОМЕСТИТЬ"
          Whitespace @66 " "
          Ident @67 "Врем"
          Semicolon @75 ";"
          Whitespace @76 " "
          KwSelect @77 "SELECT"
          Whitespace @83 " "
          FnRecordAutoNumber @84 "RECORDAUTONUMBER"
          LParen @100 "("
          RParen @101 ")"
          Whitespace @102 " "
          KwInto @103 "INTO"
          Whitespace @107 " "
          Ident @108 "Tmp"
          Newline @111 "\n"

        ---- 092 slice4 grouped by probe bilingual
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnGroupedBy @15 "СГРУППИРОВАНОПО"
          LParen @45 "("
          Ident @46 "Склад"
          RParen @56 ")"
          Semicolon @57 ";"
          Whitespace @58 " "
          KwSelect @59 "SELECT"
          Whitespace @65 " "
          FnGroupedBy @66 "GROUPEDBY"
          LParen @75 "("
          Ident @76 "Store"
          RParen @81 ")"
          Newline @82 "\n"

        ---- 093 slice4 stored data size bilingual
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnStoredDataSize @15 "РАЗМЕРХРАНИМЫХДАННЫХ"
          LParen @55 "("
          Ident @56 "Данные"
          RParen @68 ")"
          Semicolon @69 ";"
          Whitespace @70 " "
          KwSelect @71 "SELECT"
          Whitespace @77 " "
          FnStoredDataSize @78 "STOREDDATASIZE"
          LParen @92 "("
          Ident @93 "Data"
          RParen @97 ")"
          Newline @98 "\n"

        ---- 094 slice4 trigonometric and exponential functions
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          FnACos @15 "ACos"
          LParen @19 "("
          Ident @20 "X"
          RParen @21 ")"
          Comma @22 ","
          Whitespace @23 " "
          FnASin @24 "ASin"
          LParen @28 "("
          Ident @29 "X"
          RParen @30 ")"
          Comma @31 ","
          Whitespace @32 " "
          FnATan @33 "ATan"
          LParen @37 "("
          Ident @38 "X"
          RParen @39 ")"
          Comma @40 ","
          Whitespace @41 " "
          FnCos @42 "Cos"
          LParen @45 "("
          Ident @46 "X"
          RParen @47 ")"
          Comma @48 ","
          Whitespace @49 " "
          FnSin @50 "Sin"
          LParen @53 "("
          Ident @54 "X"
          RParen @55 ")"
          Comma @56 ","
          Whitespace @57 " "
          FnTan @58 "Tan"
          LParen @61 "("
          Ident @62 "X"
          RParen @63 ")"
          Comma @64 ","
          Whitespace @65 " "
          FnExp @66 "Exp"
          LParen @69 "("
          Ident @70 "X"
          RParen @71 ")"
          Comma @72 ","
          Whitespace @73 " "
          FnLog @74 "Log"
          LParen @77 "("
          Ident @78 "X"
          RParen @79 ")"
          Comma @80 ","
          Whitespace @81 " "
          FnLog10 @82 "Log10"
          LParen @87 "("
          Ident @88 "X"
          RParen @89 ")"
          Comma @90 ","
          Whitespace @91 " "
          FnPow @92 "Pow"
          LParen @95 "("
          Ident @96 "X"
          Comma @97 ","
          Whitespace @98 " "
          Decimal @99 "2"
          RParen @100 ")"
          Comma @101 ","
          Whitespace @102 " "
          FnSqrt @103 "Sqrt"
          LParen @107 "("
          Ident @108 "X"
          RParen @109 ")"
          Newline @110 "\n"

        ---- 095 slice4 date difference alternate english spelling
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          FnDateDiff @7 "DATEDIFFERENCE"
          LParen @21 "("
          Ident @22 "Start"
          Comma @27 ","
          Whitespace @28 " "
          Ident @29 "Finish"
          Comma @35 ","
          Whitespace @36 " "
          FnDay @37 "DAY"
          RParen @40 ")"
          Newline @41 "\n"

        ---- 096 slice5 information register slices russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoInformationRegister @22 "РегистрСведений"
          Dot @52 "."
          Ident @53 "Цены"
          Dot @61 "."
          VtSliceFirst @62 "СрезПервых"
          Comma @82 ","
          Whitespace @83 " "
          MdoInformationRegister @84 "РегистрСведений"
          Dot @114 "."
          Ident @115 "Цены"
          Dot @123 "."
          VtSliceLast @124 "СрезПоследних"
          Newline @150 "\n"

        ---- 097 slice5 accumulation register virtual tables russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoAccumulationRegister @22 "РегистрНакопления"
          Dot @56 "."
          Ident @57 "Товары"
          Dot @69 "."
          VtBalance @70 "Остатки"
          Comma @84 ","
          Whitespace @85 " "
          MdoAccumulationRegister @86 "РегистрНакопления"
          Dot @120 "."
          Ident @121 "Товары"
          Dot @133 "."
          VtTurnovers @134 "Обороты"
          Comma @148 ","
          Whitespace @149 " "
          MdoAccumulationRegister @150 "РегистрНакопления"
          Dot @184 "."
          Ident @185 "Товары"
          Dot @197 "."
          VtBalanceAndTurnovers @198 "ОстаткиИОбороты"
          Newline @228 "\n"

        ---- 098 slice5 accounting register virtual tables russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoAccountingRegister @22 "РегистрБухгалтерии"
          Dot @58 "."
          Ident @59 "Хозрасчетный"
          Dot @83 "."
          VtDrCrTurnovers @84 "ОборотыДтКт"
          Comma @106 ","
          Whitespace @107 " "
          MdoAccountingRegister @108 "РегистрБухгалтерии"
          Dot @144 "."
          Ident @145 "Хозрасчетный"
          Dot @169 "."
          Ident @170 "Субконто"
          Comma @186 ","
          Whitespace @187 " "
          MdoAccountingRegister @188 "РегистрБухгалтерии"
          Dot @224 "."
          Ident @225 "Хозрасчетный"
          Dot @249 "."
          Ident @250 "ДвиженияССубконто"
          Newline @284 "\n"

        ---- 099 slice5 accounting register virtual tables english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          MdoAccountingRegister @14 "AccountingRegister"
          Dot @32 "."
          Ident @33 "Main"
          Dot @37 "."
          Ident @38 "ExtDimensions"
          Comma @51 ","
          Whitespace @52 " "
          MdoAccountingRegister @53 "AccountingRegister"
          Dot @71 "."
          Ident @72 "Main"
          Dot @76 "."
          Ident @77 "RecordsWithExtDimensions"
          Newline @101 "\n"

        ---- 100 slice5 calculation register virtual tables russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoCalculationRegister @22 "РегистрРасчета"
          Dot @50 "."
          Ident @51 "Начисления"
          Dot @71 "."
          Ident @72 "ДанныеГрафика"
          Comma @98 ","
          Whitespace @99 " "
          MdoCalculationRegister @100 "РегистрРасчета"
          Dot @128 "."
          Ident @129 "Начисления"
          Dot @149 "."
          Ident @150 "ФактическийПериодДействия"
          Newline @200 "\n"

        ---- 101 slice5 calculation register virtual tables english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          MdoCalculationRegister @14 "CalculationRegister"
          Dot @33 "."
          Ident @34 "Accruals"
          Dot @42 "."
          Ident @43 "ScheduleData"
          Comma @55 ","
          Whitespace @56 " "
          MdoCalculationRegister @57 "CalculationRegister"
          Dot @76 "."
          Ident @77 "Accruals"
          Dot @85 "."
          Ident @86 "AdjustedEffectivePeriod"
          Newline @109 "\n"

        ---- 102 slice5 base register prefix stays one identifier
          MdoCalculationRegister @0 "РегистрРасчета"
          Dot @28 "."
          Ident @29 "Начисления"
          Dot @49 "."
          Ident @50 "БазаОсновныеНачисления"
          Whitespace @94 " "
          MdoCalculationRegister @95 "CalculationRegister"
          Dot @114 "."
          Ident @115 "Accruals"
          Dot @123 "."
          Ident @124 "BaseMainAccruals"
          Newline @140 "\n"

        ---- 103 slice5 sequence boundaries and route points bilingual
          MdoSequence @0 "Последовательность"
          Dot @36 "."
          Ident @37 "Проведение"
          Dot @57 "."
          Ident @58 "Границы"
          Whitespace @72 " "
          MdoSequence @73 "Sequence"
          Dot @81 "."
          Ident @82 "Posting"
          Dot @89 "."
          Ident @90 "Boundaries"
          Whitespace @100 " "
          MdoBusinessProcess @101 "БизнесПроцесс"
          Dot @127 "."
          Ident @128 "Согласование"
          Dot @152 "."
          Ident @153 "Точки"
          Whitespace @163 " "
          MdoBusinessProcess @164 "BusinessProcess"
          Dot @179 "."
          Ident @180 "Approval"
          Dot @188 "."
          Ident @189 "Points"
          Newline @195 "\n"

        ---- 104 slice5 tasks by performer bilingual
          MdoTask @0 "Задача"
          Dot @12 "."
          Ident @13 "Поручение"
          Dot @31 "."
          Ident @32 "ЗадачиПоИсполнителю"
          Whitespace @70 " "
          MdoTask @71 "Task"
          Dot @75 "."
          Ident @76 "Assignment"
          Dot @86 "."
          Ident @87 "TasksByPerformer"
          Newline @103 "\n"

        ---- 105 slice5 external data source table russian
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoExternalDataSource @22 "ВнешнийИсточникДанных"
          Dot @64 "."
          Ident @65 "Склад"
          Dot @75 "."
          Ident @76 "Таблица"
          Dot @90 "."
          Ident @91 "Позиции"
          Newline @105 "\n"

        ---- 106 slice5 external data source table english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          MdoExternalDataSource @14 "ExternalDataSource"
          Dot @32 "."
          Ident @33 "Depot"
          Dot @38 "."
          Ident @39 "Table"
          Dot @44 "."
          Ident @45 "Items"
          Newline @50 "\n"

        ---- 107 slice5 external data source cube dimension table bilingual
          MdoExternalDataSource @0 "ВнешнийИсточникДанных"
          Dot @42 "."
          Ident @43 "Склад"
          Dot @53 "."
          Ident @54 "Куб"
          Dot @60 "."
          Ident @61 "Продажи"
          Dot @75 "."
          Ident @76 "ТаблицаИзмерения"
          Dot @108 "."
          Ident @109 "Интервалы"
          Whitespace @127 " "
          MdoExternalDataSource @128 "ExternalDataSource"
          Dot @146 "."
          Ident @147 "Depot"
          Dot @152 "."
          Ident @153 "Cube"
          Dot @157 "."
          Ident @158 "Sales"
          Dot @163 "."
          Ident @164 "DimensionTable"
          Dot @178 "."
          Ident @179 "Intervals"
          Newline @188 "\n"

        ---- 108 slice5 change registration table english
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          MdoCatalog @14 "Catalog"
          Dot @21 "."
          Ident @22 "Goods"
          Dot @27 "."
          Ident @28 "Changes"
          Comma @35 ","
          Whitespace @36 " "
          MdoAccumulationRegister @37 "AccumulationRegister"
          Dot @57 "."
          Ident @58 "Stock"
          Dot @63 "."
          Ident @64 "Changes"
          Newline @71 "\n"

        ---- 109 slice5 change registration russian keeps the update keyword
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Decimal @15 "1"
          Whitespace @16 " "
          KwFrom @17 "ИЗ"
          Whitespace @21 " "
          MdoCatalog @22 "Справочник"
          Dot @42 "."
          Ident @43 "Товары"
          Dot @55 "."
          KwUpdate @56 "Изменения"
          Semicolon @74 ";"
          Whitespace @75 " "
          KwSelect @76 "ВЫБРАТЬ"
          Whitespace @90 " "
          Decimal @91 "1"
          Whitespace @92 " "
          KwFrom @93 "ИЗ"
          Whitespace @97 " "
          Ident @98 "Т"
          Whitespace @100 " "
          KwFor @101 "ДЛЯ"
          Whitespace @107 " "
          KwUpdate @108 "ИЗМЕНЕНИЯ"
          Newline @126 "\n"

        ---- 110 slice5 identifiers starting with a virtual table suffix
          Ident @0 "КубическийМетр"
          Whitespace @28 " "
          Ident @29 "ТаблицаТоваров"
          Whitespace @57 " "
          Ident @58 "ГраницыДиапазона"
          Whitespace @90 " "
          Ident @91 "ТочкаМаршрута"
          Whitespace @117 " "
          Ident @118 "Changeset"
          Whitespace @127 " "
          Ident @128 "Tableau"
          Newline @135 "\n"

    "##]];
    expected.assert_eq(&actual);
}

fn render_corpus(src: &str) -> String {
    let headers = collect_headers(src);
    let mut out = String::new();
    for (i, (h_start, header)) in headers.iter().enumerate() {
        let body_start = h_start + header.len() + 1;
        let body_end = headers.get(i + 1).map(|h| h.0).unwrap_or(src.len());
        let body = &src[body_start.min(src.len())..body_end];

        out.push_str(header);
        out.push('\n');
        for t in tokenize_sdbl(body) {
            out.push_str(&format!("  {:?} @{} {:?}\n", t.kind, t.offset, t.text.as_str()));
        }
        out.push('\n');
    }
    out
}

fn collect_headers(src: &str) -> Vec<(usize, &str)> {
    let mut headers = Vec::new();
    let mut offset = 0;
    for line in src.split_inclusive('\n') {
        let trimmed = line.trim_end_matches('\n');
        if is_header_line(trimmed) {
            headers.push((offset, trimmed));
        }
        offset += line.len();
    }
    headers
}

fn is_header_line(line: &str) -> bool {
    let Some(rest) = line.strip_prefix("---- ") else {
        return false;
    };
    let mut bytes = rest.bytes();
    matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && bytes.next() == Some(b' ')
}
