//! Byte-identity golden corpus for the SDBL lexer.
//!
//! Purpose: regression gate for structural refactors of the SDBL lexer.
//! Every entry records the exact `(kind, offset, text)` tuple sequence
//! produced by `tokenize_sdbl` for a query covering a specific slice of
//! the token surface. The baseline is captured via `expect-test`; any
//! drift must be either explained and re-approved (run with
//! `UPDATE_EXPECT=1` after justifying the change) or fixed in the
//! lexer.
//!
//! This file exists to protect the Slice 1 clean-room migration: the
//! refactor must preserve tokenisation byte-for-byte across the whole
//! corpus, regardless of which internal module hosts the regexes.

use expect_test::{expect, Expect};
use lexer::sdbl::tokenize_sdbl;

const CORPUS: &str = include_str!("fixtures/sdbl_golden_corpus.txt");

#[test]
fn golden_corpus() {
    let actual = render_corpus(CORPUS);
    let expected: Expect = expect![[r##"
        ---- 001 empty input

        ---- 002 whitespace only
          Whitespace @0 "   \t "
          Newline @5 "\n"

        ---- 003 newline only
          Newline @0 "\n"

        ---- 004 line comment
          Comment @0 "// comment line"
          Newline @15 "\n"

        ---- 005 ascii select with dot path
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Ident @7 "Name"
          Whitespace @11 " "
          KwFrom @12 "FROM"
          Whitespace @16 " "
          MdoCatalog @17 "Catalog"
          Dot @24 "."
          Ident @25 "Products"
          Newline @33 "\n"

        ---- 006 cyrillic select with dot path
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Ident @15 "Наименование"
          Whitespace @39 " "
          KwFrom @40 "ИЗ"
          Whitespace @44 " "
          MdoCatalog @45 "Справочник"
          Dot @65 "."
          Ident @66 "Товары"
          Newline @78 "\n"

        ---- 007 mixed case keywords
          KwSelect @0 "Select"
          Whitespace @6 " "
          Ident @7 "A"
          Whitespace @8 " "
          KwFrom @9 "From"
          Whitespace @13 " "
          MdoDocument @14 "Document"
          Dot @22 "."
          Ident @23 "Line"
          Newline @27 "\n"

        ---- 008 integer and float literals
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "42"
          Comma @9 ","
          Whitespace @10 " "
          Float @11 "3.14"
          Newline @15 "\n"

        ---- 009 comparison operators
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "A"
          Whitespace @7 " "
          Eq @8 "="
          Whitespace @9 " "
          Ident @10 "B"
          Whitespace @11 " "
          OpOr @12 "OR"
          Whitespace @14 " "
          Ident @15 "C"
          Whitespace @16 " "
          Neq @17 "<>"
          Whitespace @19 " "
          Ident @20 "D"
          Whitespace @21 " "
          OpOr @22 "OR"
          Whitespace @24 " "
          Ident @25 "E"
          Whitespace @26 " "
          Le @27 "<="
          Whitespace @29 " "
          Ident @30 "F"
          Whitespace @31 " "
          OpOr @32 "OR"
          Whitespace @34 " "
          Ident @35 "G"
          Whitespace @36 " "
          Ge @37 ">="
          Whitespace @39 " "
          Ident @40 "H"
          Whitespace @41 " "
          OpOr @42 "OR"
          Whitespace @44 " "
          Ident @45 "I"
          Whitespace @46 " "
          Lt @47 "<"
          Whitespace @48 " "
          Ident @49 "J"
          Whitespace @50 " "
          OpOr @51 "OR"
          Whitespace @53 " "
          Ident @54 "K"
          Whitespace @55 " "
          Gt @56 ">"
          Whitespace @57 " "
          Ident @58 "L"
          Newline @59 "\n"

        ---- 010 arithmetic operators
          Ident @0 "A"
          Whitespace @1 " "
          Plus @2 "+"
          Whitespace @3 " "
          Ident @4 "B"
          Whitespace @5 " "
          Minus @6 "-"
          Whitespace @7 " "
          Ident @8 "C"
          Whitespace @9 " "
          Star @10 "*"
          Whitespace @11 " "
          Ident @12 "D"
          Whitespace @13 " "
          Slash @14 "/"
          Whitespace @15 " "
          Ident @16 "E"
          Whitespace @17 " "
          Percent @18 "%"
          Whitespace @19 " "
          Ident @20 "F"
          Newline @21 "\n"

        ---- 011 punctuation and parens
          LParen @0 "("
          Ident @1 "A"
          Comma @2 ","
          Whitespace @3 " "
          Ident @4 "B"
          Semicolon @5 ";"
          Whitespace @6 " "
          Ident @7 "C"
          Dot @8 "."
          Ident @9 "D"
          RParen @10 ")"
          Newline @11 "\n"

        ---- 012 simple string
          String @0 "\""
          String @1 "Hello World"
          String @12 "\""
          Newline @13 "\n"

        ---- 013 string with doubled-quote escape
          String @0 "\""
          String @4 "B"
          String @5 "\""
          Newline @6 "\n"

        ---- 014 multiline string with bar
          String @0 "\""
          String @1 "line1"
          String @7 "| line2"
          String @14 "\""
          Newline @15 "\n"

        ---- 015 unterminated string at eof
          String @0 "\""
          String @1 "no end"

        ---- 016 date 8-digit
          Date @0 "'20240101'"
          Newline @10 "\n"

        ---- 017 date 14-digit
          Date @0 "'20240101120000'"
          Newline @16 "\n"

        ---- 018 parameter ascii
          Parameter @0 "&StartDate"
          Newline @10 "\n"

        ---- 019 parameter cyrillic
          Parameter @0 "&Имя"
          Newline @7 "\n"

        ---- 020 temp-table marker with identifier
          KwInto @0 "INTO"
          Whitespace @4 " "
          Hash @5 "#"
          Ident @6 "TempTable"
          Newline @15 "\n"

        ---- 021 hash standalone
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Hash @7 "#"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          Ident @14 "T"
          Newline @15 "\n"

        ---- 022 ampersand bare
          Ampersand @0 "&"
          Newline @1 "\n"

        ---- 023 bar standalone
          Bar @0 "|"
          Newline @1 "\n"

        ---- 024 identifier leading underscore and digits
          Ident @0 "_priv_1"
          Newline @7 "\n"

        ---- 025 LEFT JOIN with ON russian
          KwLeft @0 "ЛЕВОЕ"
          Whitespace @10 " "
          KwJoin @11 "СОЕДИНЕНИЕ"
          Whitespace @31 " "
          Ident @32 "T"
          Whitespace @33 " "
          KwOnOrBy @34 "ПО"
          Whitespace @38 " "
          Ident @39 "A"
          Whitespace @40 " "
          Eq @41 "="
          Whitespace @42 " "
          Ident @43 "B"
          Newline @44 "\n"

        ---- 026 INNER RIGHT FULL OUTER JOIN keywords
          KwInner @0 "INNER"
          Whitespace @5 " "
          KwRight @6 "RIGHT"
          Whitespace @11 " "
          KwFull @12 "FULL"
          Whitespace @16 " "
          KwOuter @17 "OUTER"
          Whitespace @22 " "
          KwJoin @23 "JOIN"
          Newline @27 "\n"

        ---- 027 GROUP BY HAVING
          KwGroup @0 "GROUP"
          Whitespace @5 " "
          KwOnOrBy @6 "BY"
          Whitespace @8 " "
          Ident @9 "Cat"
          Whitespace @12 " "
          KwHaving @13 "HAVING"
          Whitespace @19 " "
          FnCount @20 "COUNT"
          LParen @25 "("
          Star @26 "*"
          RParen @27 ")"
          Whitespace @28 " "
          Gt @29 ">"
          Whitespace @30 " "
          Decimal @31 "5"
          Newline @32 "\n"

        ---- 028 ORDER BY ASC DESC HIERARCHY
          KwOrder @0 "ORDER"
          Whitespace @5 " "
          KwOnOrBy @6 "BY"
          Whitespace @8 " "
          Ident @9 "Name"
          Whitespace @13 " "
          KwAsc @14 "ASC"
          Comma @17 ","
          Whitespace @18 " "
          Ident @19 "Price"
          Whitespace @24 " "
          KwDesc @25 "DESC"
          Whitespace @29 " "
          KwHierarchy @30 "HIERARCHY"
          Newline @39 "\n"

        ---- 029 UNION ALL subqueries
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwUnion @9 "UNION"
          Whitespace @14 " "
          KwAll @15 "ALL"
          Whitespace @18 " "
          KwSelect @19 "SELECT"
          Whitespace @25 " "
          Decimal @26 "2"
          Newline @27 "\n"

        ---- 030 DISTINCT TOP literal
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          KwDistinct @7 "DISTINCT"
          Whitespace @15 " "
          KwTop @16 "TOP"
          Whitespace @19 " "
          Decimal @20 "100"
          Whitespace @23 " "
          Ident @24 "Name"
          Newline @28 "\n"

        ---- 031 BETWEEN AND predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "P"
          Whitespace @7 " "
          KwBetween @8 "BETWEEN"
          Whitespace @15 " "
          Decimal @16 "1"
          Whitespace @17 " "
          OpAnd @18 "AND"
          Whitespace @21 " "
          Decimal @22 "10"
          Newline @24 "\n"

        ---- 032 LIKE ESCAPE predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "N"
          Whitespace @7 " "
          KwLike @8 "LIKE"
          Whitespace @12 " "
          String @13 "\""
          String @14 "%X%"
          String @17 "\""
          Whitespace @18 " "
          KwEscape @19 "ESCAPE"
          Whitespace @25 " "
          String @26 "\""
          String @27 "!"
          String @28 "\""
          Newline @29 "\n"

        ---- 033 IS NULL predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "X"
          Whitespace @7 " "
          KwIs @8 "IS"
          Whitespace @10 " "
          LitNull @11 "NULL"
          Newline @15 "\n"

        ---- 034 CASE WHEN THEN ELSE END
          KwCase @0 "CASE"
          Whitespace @4 " "
          KwWhen @5 "WHEN"
          Whitespace @9 " "
          Ident @10 "X"
          Whitespace @11 " "
          Gt @12 ">"
          Whitespace @13 " "
          Decimal @14 "0"
          Whitespace @15 " "
          KwThen @16 "THEN"
          Whitespace @20 " "
          Decimal @21 "1"
          Whitespace @22 " "
          KwElse @23 "ELSE"
          Whitespace @27 " "
          Decimal @28 "0"
          Whitespace @29 " "
          KwEnd @30 "END"
          Newline @33 "\n"

        ---- 035 CAST AS NUMBER
          KwCast @0 "CAST"
          LParen @4 "("
          Ident @5 "P"
          Whitespace @6 " "
          KwAs @7 "AS"
          Whitespace @9 " "
          TypeNumber @10 "NUMBER"
          LParen @16 "("
          Decimal @17 "15"
          Comma @19 ","
          Whitespace @20 " "
          Decimal @21 "2"
          RParen @22 ")"
          RParen @23 ")"
          Newline @24 "\n"

        ---- 036 REFS predicate
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "R"
          Whitespace @7 " "
          KwRefs @8 "REFS"
          Whitespace @12 " "
          MdoCatalog @13 "Catalog"
          Dot @20 "."
          Ident @21 "Products"
          Newline @29 "\n"

        ---- 037 IN predicate with parameter
          KwWhere @0 "WHERE"
          Whitespace @5 " "
          Ident @6 "C"
          Whitespace @7 " "
          KwIn @8 "IN"
          Whitespace @10 " "
          LParen @11 "("
          Parameter @12 "&List"
          RParen @17 ")"
          Newline @18 "\n"

        ---- 038 INTO temp and DROP russian
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwInto @9 "ПОМЕСТИТЬ"
          Whitespace @27 " "
          Hash @28 "#"
          Ident @29 "T"
          Semicolon @30 ";"
          Whitespace @31 " "
          KwDrop @32 "УНИЧТОЖИТЬ"
          Whitespace @52 " "
          Hash @53 "#"
          Ident @54 "T"
          Newline @55 "\n"

        ---- 039 FOR UPDATE INDEX BY ONLY ALLOWED OVERALL
          KwFor @0 "FOR"
          Whitespace @3 " "
          KwUpdate @4 "UPDATE"
          Whitespace @10 " "
          KwIndex @11 "INDEX"
          Whitespace @16 " "
          KwOnOrBy @17 "BY"
          Whitespace @19 " "
          Ident @20 "T"
          Dot @21 "."
          Ident @22 "F"
          Whitespace @23 " "
          KwOnly @24 "ONLY"
          Whitespace @28 " "
          KwAllowed @29 "ALLOWED"
          Whitespace @36 " "
          KwOverall @37 "OVERALL"
          Newline @44 "\n"

        ---- 040 TOTALS AUTOORDER PERIODS russian
          KwTotals @0 "ИТОГИ"
          Whitespace @10 " "
          FnSum @11 "СУММА"
          LParen @21 "("
          Ident @22 "X"
          RParen @23 ")"
          Whitespace @24 " "
          KwOnOrBy @25 "ПО"
          Whitespace @29 " "
          KwOverall @30 "ОБЩИЕ"
          Whitespace @40 " "
          KwAutoOrder @41 "АВТОУПОРЯДОЧИВАНИЕ"
          Whitespace @77 " "
          KwPeriods @78 "ПЕРИОДЫ"
          LParen @92 "("
          FnDay @93 "ДЕНЬ"
          Comma @101 ","
          Whitespace @102 " "
          FnDateTime @103 "ДАТАВРЕМЯ"
          LParen @121 "("
          Decimal @122 "2024"
          Comma @126 ","
          Whitespace @127 " "
          Decimal @128 "1"
          Comma @129 ","
          Whitespace @130 " "
          Decimal @131 "1"
          RParen @132 ")"
          Comma @133 ","
          Whitespace @134 " "
          Parameter @135 "&End"
          RParen @139 ")"
          Newline @140 "\n"

        ---- 041 aggregate functions
          FnSum @0 "SUM"
          LParen @3 "("
          Ident @4 "A"
          RParen @5 ")"
          Whitespace @6 " "
          FnAvg @7 "AVG"
          LParen @10 "("
          Ident @11 "B"
          RParen @12 ")"
          Whitespace @13 " "
          FnMin @14 "MIN"
          LParen @17 "("
          Ident @18 "C"
          RParen @19 ")"
          Whitespace @20 " "
          FnMax @21 "MAX"
          LParen @24 "("
          Ident @25 "D"
          RParen @26 ")"
          Whitespace @27 " "
          FnCount @28 "COUNT"
          LParen @33 "("
          Star @34 "*"
          RParen @35 ")"
          Newline @36 "\n"

        ---- 042 date functions
          FnYear @0 "YEAR"
          LParen @4 "("
          Ident @5 "D"
          RParen @6 ")"
          Whitespace @7 " "
          FnQuarter @8 "QUARTER"
          LParen @15 "("
          Ident @16 "D"
          RParen @17 ")"
          Whitespace @18 " "
          FnMonth @19 "MONTH"
          LParen @24 "("
          Ident @25 "D"
          RParen @26 ")"
          Whitespace @27 " "
          FnWeek @28 "WEEK"
          LParen @32 "("
          Ident @33 "D"
          RParen @34 ")"
          Whitespace @35 " "
          FnDay @36 "DAY"
          LParen @39 "("
          Ident @40 "D"
          RParen @41 ")"
          Whitespace @42 " "
          FnHour @43 "HOUR"
          LParen @47 "("
          Ident @48 "D"
          RParen @49 ")"
          Whitespace @50 " "
          FnMinute @51 "MINUTE"
          LParen @57 "("
          Ident @58 "D"
          RParen @59 ")"
          Whitespace @60 " "
          FnSecond @61 "SECOND"
          LParen @67 "("
          Ident @68 "D"
          RParen @69 ")"
          Whitespace @70 " "
          FnWeekDay @71 "WEEKDAY"
          LParen @78 "("
          Ident @79 "D"
          RParen @80 ")"
          Whitespace @81 " "
          FnDayOfYear @82 "DAYOFYEAR"
          LParen @91 "("
          Ident @92 "D"
          RParen @93 ")"
          Newline @94 "\n"

        ---- 043 date arithmetic functions
          FnDateAdd @0 "DATEADD"
          LParen @7 "("
          Ident @8 "D"
          Comma @9 ","
          Whitespace @10 " "
          FnYear @11 "YEAR"
          Comma @15 ","
          Whitespace @16 " "
          Decimal @17 "1"
          RParen @18 ")"
          Whitespace @19 " "
          FnDateDiff @20 "DATEDIFF"
          LParen @28 "("
          Ident @29 "D1"
          Comma @31 ","
          Whitespace @32 " "
          Ident @33 "D2"
          Comma @35 ","
          Whitespace @36 " "
          FnDay @37 "DAY"
          RParen @40 ")"
          Whitespace @41 " "
          FnBeginOfPeriod @42 "BEGINOFPERIOD"
          LParen @55 "("
          Ident @56 "D"
          Comma @57 ","
          Whitespace @58 " "
          FnQuarter @59 "QUARTER"
          RParen @66 ")"
          Whitespace @67 " "
          FnEndOfPeriod @68 "ENDOFPERIOD"
          LParen @79 "("
          Ident @80 "D"
          Comma @81 ","
          Whitespace @82 " "
          FnMonth @83 "MONTH"
          RParen @88 ")"
          Newline @89 "\n"

        ---- 044 string functions
          FnSubstring @0 "SUBSTRING"
          LParen @9 "("
          Ident @10 "S"
          Comma @11 ","
          Whitespace @12 " "
          Decimal @13 "1"
          Comma @14 ","
          Whitespace @15 " "
          Decimal @16 "10"
          RParen @18 ")"
          Whitespace @19 " "
          FnStringLength @20 "STRINGLENGTH"
          LParen @32 "("
          Ident @33 "S"
          RParen @34 ")"
          Whitespace @35 " "
          FnStrFind @36 "STRFIND"
          LParen @43 "("
          Ident @44 "S"
          Comma @45 ","
          Whitespace @46 " "
          String @47 "\""
          String @48 "x"
          String @49 "\""
          RParen @50 ")"
          Whitespace @51 " "
          FnUpper @52 "UPPER"
          LParen @57 "("
          Ident @58 "S"
          RParen @59 ")"
          Whitespace @60 " "
          FnLower @61 "LOWER"
          LParen @66 "("
          Ident @67 "S"
          RParen @68 ")"
          Whitespace @69 " "
          FnTrimAll @70 "TRIMALL"
          LParen @77 "("
          Ident @78 "S"
          RParen @79 ")"
          Whitespace @80 " "
          FnTrimL @81 "TRIML"
          LParen @86 "("
          Ident @87 "S"
          RParen @88 ")"
          Whitespace @89 " "
          FnTrimR @90 "TRIMR"
          LParen @95 "("
          Ident @96 "S"
          RParen @97 ")"
          Newline @98 "\n"

        ---- 045 math functions
          FnRound @0 "ROUND"
          LParen @5 "("
          Ident @6 "X"
          RParen @7 ")"
          Whitespace @8 " "
          FnInt @9 "INT"
          LParen @12 "("
          Ident @13 "X"
          RParen @14 ")"
          Whitespace @15 " "
          FnLog @16 "LOG"
          LParen @19 "("
          Ident @20 "X"
          RParen @21 ")"
          Whitespace @22 " "
          FnLog10 @23 "LOG10"
          LParen @28 "("
          Ident @29 "X"
          RParen @30 ")"
          Whitespace @31 " "
          FnPow @32 "POW"
          LParen @35 "("
          Ident @36 "X"
          Comma @37 ","
          Whitespace @38 " "
          Decimal @39 "2"
          RParen @40 ")"
          Whitespace @41 " "
          FnSqrt @42 "SQRT"
          LParen @46 "("
          Ident @47 "X"
          RParen @48 ")"
          Newline @49 "\n"

        ---- 046 type and null functions
          FnValueType @0 "VALUETYPE"
          LParen @9 "("
          Ident @10 "X"
          RParen @11 ")"
          Whitespace @12 " "
          FnPresentation @13 "PRESENTATION"
          LParen @25 "("
          Ident @26 "X"
          RParen @27 ")"
          Whitespace @28 " "
          FnRefPresentation @29 "REFPRESENTATION"
          LParen @44 "("
          Ident @45 "X"
          RParen @46 ")"
          Whitespace @47 " "
          FnIsNull @48 "ISNULL"
          LParen @54 "("
          Ident @55 "X"
          Comma @56 ","
          Whitespace @57 " "
          Decimal @58 "0"
          RParen @59 ")"
          Whitespace @60 " "
          FnEmptyTable @61 "EMPTYTABLE"
          Whitespace @71 " "
          FnEmptyRef @72 "EMPTYREF"
          Whitespace @80 " "
          FnUUID @81 "UUID"
          Newline @85 "\n"

        ---- 047 metadata objects dot paths
          MdoCatalog @0 "Catalog"
          Dot @7 "."
          Ident @8 "C"
          Whitespace @9 " "
          MdoDocument @10 "Document"
          Dot @18 "."
          Ident @19 "D"
          Whitespace @20 " "
          MdoInformationRegister @21 "InformationRegister"
          Dot @40 "."
          Ident @41 "I"
          Whitespace @42 " "
          MdoAccumulationRegister @43 "AccumulationRegister"
          Dot @63 "."
          Ident @64 "A"
          Whitespace @65 " "
          MdoAccountingRegister @66 "AccountingRegister"
          Dot @84 "."
          Ident @85 "R"
          Whitespace @86 " "
          MdoCalculationRegister @87 "CalculationRegister"
          Dot @106 "."
          Ident @107 "CR"
          Whitespace @109 " "
          MdoChartOfAccounts @110 "ChartOfAccounts"
          Dot @125 "."
          Ident @126 "COA"
          Whitespace @129 " "
          MdoChartOfCalculationTypes @130 "ChartOfCalculationTypes"
          Dot @153 "."
          Ident @154 "CCT"
          Whitespace @157 " "
          MdoChartOfCharacteristicTypes @158 "ChartOfCharacteristicTypes"
          Dot @184 "."
          Ident @185 "CCH"
          Whitespace @188 " "
          MdoEnum @189 "Enum"
          Dot @193 "."
          Ident @194 "E"
          Whitespace @195 " "
          MdoBusinessProcess @196 "BusinessProcess"
          Dot @211 "."
          Ident @212 "BP"
          Whitespace @214 " "
          MdoTask @215 "Task"
          Dot @219 "."
          Ident @220 "T"
          Whitespace @221 " "
          MdoConstant @222 "Constant"
          Dot @230 "."
          Ident @231 "K"
          Whitespace @232 " "
          MdoSequence @233 "Sequence"
          Dot @241 "."
          Ident @242 "S"
          Whitespace @243 " "
          MdoExternalDataSource @244 "ExternalDataSource"
          Dot @262 "."
          Ident @263 "X"
          Newline @264 "\n"

        ---- 048 virtual tables
          MdoAccumulationRegister @0 "AccumulationRegister"
          Dot @20 "."
          Ident @21 "Stock"
          Dot @26 "."
          VtBalance @27 "Balance"
          Whitespace @34 " "
          MdoAccumulationRegister @35 "AccumulationRegister"
          Dot @55 "."
          Ident @56 "Stock"
          Dot @61 "."
          VtTurnovers @62 "Turnovers"
          Whitespace @71 " "
          MdoAccumulationRegister @72 "AccumulationRegister"
          Dot @92 "."
          Ident @93 "Stock"
          Dot @98 "."
          VtBalanceAndTurnovers @99 "BalanceAndTurnovers"
          Whitespace @118 " "
          MdoInformationRegister @119 "InformationRegister"
          Dot @138 "."
          Ident @139 "Prices"
          Dot @145 "."
          VtSliceLast @146 "SliceLast"
          Whitespace @155 " "
          MdoInformationRegister @156 "InformationRegister"
          Dot @175 "."
          Ident @176 "Prices"
          Dot @182 "."
          VtSliceFirst @183 "SliceFirst"
          Whitespace @193 " "
          MdoAccountingRegister @194 "AccountingRegister"
          Dot @212 "."
          Ident @213 "Main"
          Dot @217 "."
          VtDrCrTurnovers @218 "DrCrTurnovers"
          Newline @231 "\n"

        ---- 049 type literals and bool and null literals
          KwType @0 "TYPE"
          LParen @4 "("
          TypeBoolean @5 "Boolean"
          RParen @12 ")"
          Whitespace @13 " "
          KwType @14 "TYPE"
          LParen @18 "("
          TypeNumber @19 "Number"
          RParen @25 ")"
          Whitespace @26 " "
          KwType @27 "TYPE"
          LParen @31 "("
          TypeString @32 "String"
          RParen @38 ")"
          Whitespace @39 " "
          KwType @40 "TYPE"
          LParen @44 "("
          TypeDate @45 "Date"
          RParen @49 ")"
          Whitespace @50 " "
          LitTrue @51 "TRUE"
          Whitespace @55 " "
          LitFalse @56 "FALSE"
          Whitespace @61 " "
          LitTrue @62 "ИСТИНА"
          Whitespace @74 " "
          LitFalse @75 "ЛОЖЬ"
          Whitespace @83 " "
          LitNull @84 "NULL"
          Whitespace @88 " "
          LitUndefined @89 "Неопределено"
          Whitespace @113 " "
          KwValue @114 "VALUE"
          LParen @119 "("
          MdoEnum @120 "Enum"
          Dot @124 "."
          Ident @125 "Status"
          Dot @131 "."
          Ident @132 "Done"
          RParen @136 ")"
          Newline @137 "\n"

        ---- 050 logical operators and period types
          Ident @0 "A"
          Whitespace @1 " "
          OpAnd @2 "AND"
          Whitespace @5 " "
          Ident @6 "B"
          Whitespace @7 " "
          OpOr @8 "OR"
          Whitespace @10 " "
          OpNot @11 "NOT"
          Whitespace @14 " "
          Ident @15 "C"
          Semicolon @16 ";"
          Whitespace @17 " "
          PeriodTenDays @18 "ДЕКАДА"
          Whitespace @30 " "
          PeriodHalfYear @31 "ПОЛУГОДИЕ"
          Newline @49 "\n"

        ---- 051 russian alias keyword
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          Ident @15 "П"
          Dot @17 "."
          Ident @18 "Наименование"
          Whitespace @42 " "
          KwAs @43 "КАК"
          Whitespace @49 " "
          Ident @50 "Наименование"
          Whitespace @74 " "
          KwFrom @75 "ИЗ"
          Whitespace @79 " "
          MdoCatalog @80 "Справочник"
          Dot @100 "."
          Ident @101 "Продукты"
          Whitespace @117 " "
          KwAs @118 "КАК"
          Whitespace @124 " "
          Ident @125 "П"
          Newline @127 "\n"

        ---- 052 english join on
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Ident @7 "t1"
          Dot @9 "."
          Ident @10 "id"
          Whitespace @12 " "
          KwFrom @13 "FROM"
          Whitespace @17 " "
          MdoCatalog @18 "Catalog"
          Dot @25 "."
          Ident @26 "Products"
          Whitespace @34 " "
          KwAs @35 "AS"
          Whitespace @37 " "
          Ident @38 "t1"
          Whitespace @40 " "
          KwInner @41 "INNER"
          Whitespace @46 " "
          KwJoin @47 "JOIN"
          Whitespace @51 " "
          MdoCatalog @52 "Catalog"
          Dot @59 "."
          Ident @60 "Prices"
          Whitespace @66 " "
          KwAs @67 "AS"
          Whitespace @69 " "
          Ident @70 "t2"
          Whitespace @72 " "
          KwOnOrBy @73 "ON"
          Whitespace @75 " "
          Ident @76 "t2"
          Dot @78 "."
          Ident @79 "product"
          Whitespace @86 " "
          Eq @87 "="
          Whitespace @88 " "
          Ident @89 "t1"
          Dot @91 "."
          Ident @92 "ref"
          Newline @95 "\n"

        ---- 053 russian clause keywords
          KwSelect @0 "ВЫБРАТЬ"
          Whitespace @14 " "
          KwDistinct @15 "РАЗЛИЧНЫЕ"
          Whitespace @33 " "
          KwTop @34 "ПЕРВЫЕ"
          Whitespace @46 " "
          Decimal @47 "5"
          Whitespace @48 " "
          Ident @49 "Имя"
          Whitespace @55 " "
          KwWhere @56 "ГДЕ"
          Whitespace @62 " "
          Ident @63 "X"
          Whitespace @64 " "
          Gt @65 ">"
          Whitespace @66 " "
          Decimal @67 "0"
          Whitespace @68 " "
          KwGroup @69 "СГРУППИРОВАТЬ"
          Whitespace @95 " "
          KwOnOrBy @96 "ПО"
          Whitespace @100 " "
          Ident @101 "Y"
          Whitespace @102 " "
          KwHaving @103 "ИМЕЮЩИЕ"
          Whitespace @117 " "
          FnSum @118 "СУММА"
          LParen @128 "("
          Ident @129 "Y"
          RParen @130 ")"
          Whitespace @131 " "
          Gt @132 ">"
          Whitespace @133 " "
          Decimal @134 "0"
          Whitespace @135 " "
          KwOrder @136 "УПОРЯДОЧИТЬ"
          Whitespace @158 " "
          KwOnOrBy @159 "ПО"
          Whitespace @163 " "
          Ident @164 "Y"
          Whitespace @165 " "
          KwUnion @166 "ОБЪЕДИНИТЬ"
          Whitespace @186 " "
          KwAll @187 "ВСЕ"
          Whitespace @193 " "
          KwSelect @194 "ВЫБРАТЬ"
          Whitespace @208 " "
          Decimal @209 "2"
          Newline @210 "\n"

        ---- 054 russian predicates and case
          KwWhere @0 "ГДЕ"
          Whitespace @6 " "
          Ident @7 "X"
          Whitespace @8 " "
          KwBetween @9 "МЕЖДУ"
          Whitespace @19 " "
          Decimal @20 "1"
          Whitespace @21 " "
          OpAnd @22 "И"
          Whitespace @24 " "
          Decimal @25 "10"
          Whitespace @27 " "
          OpOr @28 "ИЛИ"
          Whitespace @34 " "
          OpNot @35 "НЕ"
          Whitespace @39 " "
          Ident @40 "Y"
          Whitespace @41 " "
          KwIs @42 "ЕСТЬ"
          Whitespace @50 " "
          LitNull @51 "NULL"
          Whitespace @55 " "
          OpAnd @56 "И"
          Whitespace @58 " "
          Ident @59 "Z"
          Whitespace @60 " "
          KwLike @61 "ПОДОБНО"
          Whitespace @75 " "
          String @76 "\""
          String @77 "%x%"
          String @80 "\""
          Whitespace @81 " "
          OpAnd @82 "И"
          Whitespace @84 " "
          Ident @85 "W"
          Whitespace @86 " "
          KwIn @87 "В"
          Whitespace @89 " "
          LParen @90 "("
          Parameter @91 "&P"
          RParen @93 ")"
          Whitespace @94 " "
          KwCase @95 "ВЫБОР"
          Whitespace @105 " "
          KwWhen @106 "КОГДА"
          Whitespace @116 " "
          Ident @117 "A"
          Whitespace @118 " "
          Gt @119 ">"
          Whitespace @120 " "
          Decimal @121 "0"
          Whitespace @122 " "
          KwThen @123 "ТОГДА"
          Whitespace @133 " "
          Decimal @134 "1"
          Whitespace @135 " "
          KwElse @136 "ИНАЧЕ"
          Whitespace @146 " "
          Decimal @147 "0"
          Whitespace @148 " "
          KwEnd @149 "КОНЕЦ"
          Newline @159 "\n"

        ---- 055 english totals
          KwTotals @0 "TOTALS"
          Whitespace @6 " "
          FnSum @7 "SUM"
          LParen @10 "("
          Ident @11 "X"
          RParen @12 ")"
          Newline @13 "\n"

        ---- 056 russian join family
          KwInner @0 "ВНУТРЕННЕЕ"
          Whitespace @20 " "
          KwRight @21 "ПРАВОЕ"
          Whitespace @33 " "
          KwFull @34 "ПОЛНОЕ"
          Whitespace @46 " "
          KwOuter @47 "ВНЕШНЕЕ"
          Whitespace @61 " "
          KwJoin @62 "СОЕДИНЕНИЕ"
          Newline @82 "\n"

        ---- 057 english left join
          KwSelect @0 "SELECT"
          Whitespace @6 " "
          Decimal @7 "1"
          Whitespace @8 " "
          KwFrom @9 "FROM"
          Whitespace @13 " "
          Ident @14 "T"
          Whitespace @15 " "
          KwLeft @16 "LEFT"
          Whitespace @20 " "
          KwJoin @21 "JOIN"
          Whitespace @25 " "
          Ident @26 "U"
          Whitespace @27 " "
          KwOnOrBy @28 "ON"
          Whitespace @30 " "
          Ident @31 "T"
          Dot @32 "."
          Ident @33 "id"
          Whitespace @35 " "
          Eq @36 "="
          Whitespace @37 " "
          Ident @38 "U"
          Dot @39 "."
          Ident @40 "id"
          Newline @42 "\n"

    "##]];
    expected.assert_eq(&actual);
}

fn render_corpus(src: &str) -> String {
    let headers = collect_headers(src);
    let mut out = String::new();
    for (i, (h_start, header)) in headers.iter().enumerate() {
        let body_start = h_start + header.len() + 1;
        let body_end = headers.get(i + 1).map(|h| h.0).unwrap_or(src.len());
        let body = &src[body_start.min(src.len())..body_end];

        out.push_str(header);
        out.push('\n');
        for t in tokenize_sdbl(body) {
            out.push_str(&format!("  {:?} @{} {:?}\n", t.kind, t.offset, t.text.as_str()));
        }
        out.push('\n');
    }
    out
}

fn collect_headers(src: &str) -> Vec<(usize, &str)> {
    let mut headers = Vec::new();
    let mut offset = 0;
    for line in src.split_inclusive('\n') {
        let trimmed = line.trim_end_matches('\n');
        if is_header_line(trimmed) {
            headers.push((offset, trimmed));
        }
        offset += line.len();
    }
    headers
}

// Anchor a header as `---- NNN ` (three ASCII digits + space) so a body
// line that happens to start with `---- ` cannot split an entry.
fn is_header_line(line: &str) -> bool {
    let Some(rest) = line.strip_prefix("---- ") else {
        return false;
    };
    let mut bytes = rest.bytes();
    matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && matches!(bytes.next(), Some(b) if b.is_ascii_digit())
        && bytes.next() == Some(b' ')
}
