[package]
name = "ide-db"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hir.workspace = true
hir-def.workspace = true
sdbl-hir.workspace = true
base-db.workspace = true
bsl-metadata.workspace = true
syntax.workspace = true
vfs.workspace = true
salsa.workspace = true
rustc-hash.workspace = true
dashmap.workspace = true
indexmap.workspace = true
tracing.workspace = true
dataflow.workspace = true
cfg.workspace = true

[dev-dependencies]
expect-test.workspace = true
criterion.workspace = true

[[bench]]
name = "salsa_incremental"
harness = false
