use parser_error::ParseError;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Event {
    Start { kind: NodeKind, forward_parent: Option<usize> },
    Finish,
    Token { kind: lexer::TokenKind },
    Placeholder,
    Error(ParseError),
    ErrorWithSpan { start_token: usize, err: ParseError },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeKind {
    SourceFile,

    ProcedureDef,
    FunctionDef,
    VarDef,
    ParamList,
    Param,
    Annotation,
    AnnotationParams,
    AnnotationParam,
    CompilerDirective,

    StmtList,
    AssignStmt,
    CallStmt,
    ReturnStmt,
    IfStmt,
    ElseIfClause,
    ElseClause,
    WhileStmt,
    ForStmt,
    ForEachStmt,
    TryStmt,
    ExceptClause,
    RaiseStmt,
    ExecuteStmt,
    BreakStmt,
    ContinueStmt,
    GotoStmt,
    LabelStmt,
    AddHandlerStmt,
    RemoveHandlerStmt,
    EmptyStmt,

    Expr,
    BinaryExpr,
    UnaryExpr,
    TernaryExpr,
    CallExpr,
    IndexExpr,
    FieldExpr,
    NewExpr,
    AwaitExpr,
    ParenExpr,
    Literal,
    Ident,
    ArgList,

    PreIfDir,
    PreElsIfClause,
    PreElseClause,
    PreRegionDir,
    PreDeleteDir,
    PreInsertDir,
    PreExpr,
    PreLogicalExpr,
    PreLogicalOperand,
    PreSymbol,
    PreBoolOp,

    SdblQueryPackage,
    SdblSelectQuery,
    SdblSubquery,
    SdblUnionClause,
    SdblQuery,
    SdblQueryExtension,
    SdblLimitations,
    SdblTopClause,
    SdblSelectClause,
    SdblFieldList,
    SdblSelectedField,
    SdblAlias,
    SdblAsteriskField,
    SdblIntoClause,
    SdblTempTableName,
    SdblFromClause,
    SdblDataSource,
    SdblTableRef,
    SdblJoinClause,
    SdblWhereClause,
    SdblGroupClause,
    SdblOrderClause,
    SdblHavingClause,
    SdblForUpdate,
    SdblIndexBy,
    SdblAutoorder,
    SdblTotalsBy,
    SdblExpr,
    SdblLogicalOrExpr,
    SdblLogicalAndExpr,
    SdblNotExpr,
    SdblComparisonExpr,
    SdblInExpr,
    SdblInHierarchyExpr,
    SdblIsNullExpr,
    SdblBetweenExpr,
    SdblLikeExpr,
    SdblRefsExpr,
    SdblAdditiveExpr,
    SdblMultiplicativeExpr,
    SdblUnaryExpr,
    SdblParenExpr,
    SdblTupleExpr,
    SdblSubqueryExpr,
    SdblColumnRef,
    SdblInlineTableFields,
    SdblFunctionCall,
    SdblCaseExpr,
    SdblWhenClause,
    SdblLiteral,
    SdblMultiString,
    SdblParameter,
    SdblType,
    SdblDropQuery,
    SdblMissingArg,
    SdblError,

    Error,
    Comment,
}
