[package]
name = "hir-ty"
version = "0.1.28"
edition = "2021"
authors = ["BSL Analyzer Contributors"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/1c-syntax/bsl-analyzer"

[dependencies]
cfg-types = { path = "../cfg-types" }
hir-def = { path = "../hir-def" }
base-db = { path = "../base-db" }
bsl-platform = { path = "../bsl-platform" }
syntax = { path = "../syntax" }
intern = { path = "../intern" }
stdx = { path = "../stdx" }
vfs = { path = "../vfs" }

salsa.workspace = true
rustc-hash.workspace = true
la-arena.workspace = true
tracing.workspace = true
smol_str.workspace = true

[dev-dependencies]
expect-test = "1.5.0"
