[package]
name = "base-db"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
syntax.workspace = true
vfs.workspace = true
parser.workspace = true
rustc-hash.workspace = true
dashmap.workspace = true
tracing.workspace = true
salsa.workspace = true

[dev-dependencies]
expect-test.workspace = true
