[package]
name = "ide"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-db.workspace = true
ide-diagnostics.workspace = true
ide-assists.workspace = true
hir.workspace = true
syntax.workspace = true
vfs.workspace = true
stdx.workspace = true
sdbl-hir.workspace = true
triomphe.workspace = true
tracing.workspace = true
either = "1.9"
rustc-hash = "2.1"

[dev-dependencies]
expect-test.workspace = true
test-fixture.workspace = true
